# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: developer/v1/echo.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'developer/v1/echo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x64\x65veloper/v1/echo.proto\x12\x18\x61ppsets.api.developer.v1\x1a\x1cgoogle/api/annotations.proto\"%\n\rStringMessage\x12\x14\n\x05value\x18\x01 \x01(\tR\x05value2\x80\x01\n\x0b\x45\x63hoService\x12q\n\x04\x45\x63ho\x12\'.appsets.api.developer.v1.StringMessage\x1a\'.appsets.api.developer.v1.StringMessage\"\x17\x82\xd3\xe4\x93\x02\x11\"\x0c/api/v1/echo:\x01*B9Z7github.com/appsets/protocol/go/developer/v1;developerpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'developer.v1.echo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z7github.com/appsets/protocol/go/developer/v1;developerpb'
  _globals['_ECHOSERVICE'].methods_by_name['Echo']._loaded_options = None
  _globals['_ECHOSERVICE'].methods_by_name['Echo']._serialized_options = b'\202\323\344\223\002\021\"\014/api/v1/echo:\001*'
  _globals['_STRINGMESSAGE']._serialized_start=83
  _globals['_STRINGMESSAGE']._serialized_end=120
  _globals['_ECHOSERVICE']._serialized_start=123
  _globals['_ECHOSERVICE']._serialized_end=251
# @@protoc_insertion_point(module_scope)
