# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: developer/v1/organization.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'developer/v1/organization.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x64\x65veloper/v1/organization.proto\x12\x18\x61ppsets.api.developer.v1\x1a\x1cgoogle/api/annotations.proto\"\x8d\x01\n\x19\x43reateOrganizationRequest\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n\x04\x63ode\x18\x02 \x01(\tR\x04\x63ode\x12\x12\n\x04name\x18\x03 \x01(\tR\x04name\x12\x19\n\x08owned_by\x18\x04 \x01(\tR\x07ownedBy\x12\x1d\n\ncreated_by\x18\x05 \x01(\tR\tcreatedBy\"\x1c\n\x1a\x43reateOrganizationResponse2\xb3\x01\n\x13OrganizationService\x12\x9b\x01\n\x06\x43reate\x12\x33.appsets.api.developer.v1.CreateOrganizationRequest\x1a\x34.appsets.api.developer.v1.CreateOrganizationResponse\"&\x82\xd3\xe4\x93\x02 \"\x1b/api/v1/organization/create:\x01*B9Z7github.com/appsets/protocol/go/developer/v1;developerpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'developer.v1.organization_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z7github.com/appsets/protocol/go/developer/v1;developerpb'
  _globals['_ORGANIZATIONSERVICE'].methods_by_name['Create']._loaded_options = None
  _globals['_ORGANIZATIONSERVICE'].methods_by_name['Create']._serialized_options = b'\202\323\344\223\002 \"\033/api/v1/organization/create:\001*'
  _globals['_CREATEORGANIZATIONREQUEST']._serialized_start=92
  _globals['_CREATEORGANIZATIONREQUEST']._serialized_end=233
  _globals['_CREATEORGANIZATIONRESPONSE']._serialized_start=235
  _globals['_CREATEORGANIZATIONRESPONSE']._serialized_end=263
  _globals['_ORGANIZATIONSERVICE']._serialized_start=266
  _globals['_ORGANIZATIONSERVICE']._serialized_end=445
# @@protoc_insertion_point(module_scope)
