# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from developer.v1 import schedule_pb2 as developer_dot_v1_dot_schedule__pb2


class ScheduleServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ValidatePurchases = channel.unary_unary(
                '/appsets.api.developer.v1.ScheduleService/ValidatePurchases',
                request_serializer=developer_dot_v1_dot_schedule__pb2.ValidatePurchasesRequest.SerializeToString,
                response_deserializer=developer_dot_v1_dot_schedule__pb2.ValidatePurchasesResponse.FromString,
                _registered_method=True)


class ScheduleServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ValidatePurchases(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ScheduleServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ValidatePurchases': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidatePurchases,
                    request_deserializer=developer_dot_v1_dot_schedule__pb2.ValidatePurchasesRequest.FromString,
                    response_serializer=developer_dot_v1_dot_schedule__pb2.ValidatePurchasesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'appsets.api.developer.v1.ScheduleService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('appsets.api.developer.v1.ScheduleService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ScheduleService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ValidatePurchases(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/appsets.api.developer.v1.ScheduleService/ValidatePurchases',
            developer_dot_v1_dot_schedule__pb2.ValidatePurchasesRequest.SerializeToString,
            developer_dot_v1_dot_schedule__pb2.ValidatePurchasesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
