# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: developer/v1/schedule.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'developer/v1/schedule.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x64\x65veloper/v1/schedule.proto\x12\x18\x61ppsets.api.developer.v1\x1a\x1cgoogle/api/annotations.proto\"\x1a\n\x18ValidatePurchasesRequest\"\x1b\n\x19ValidatePurchasesResponse2\xbf\x01\n\x0fScheduleService\x12\xab\x01\n\x11ValidatePurchases\x12\x32.appsets.api.developer.v1.ValidatePurchasesRequest\x1a\x33.appsets.api.developer.v1.ValidatePurchasesResponse\"-\x82\xd3\xe4\x93\x02\'\"\"/api/v1/schedule/purchase/validate:\x01*B9Z7github.com/appsets/protocol/go/developer/v1;developerpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'developer.v1.schedule_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z7github.com/appsets/protocol/go/developer/v1;developerpb'
  _globals['_SCHEDULESERVICE'].methods_by_name['ValidatePurchases']._loaded_options = None
  _globals['_SCHEDULESERVICE'].methods_by_name['ValidatePurchases']._serialized_options = b'\202\323\344\223\002\'\"\"/api/v1/schedule/purchase/validate:\001*'
  _globals['_VALIDATEPURCHASESREQUEST']._serialized_start=87
  _globals['_VALIDATEPURCHASESREQUEST']._serialized_end=113
  _globals['_VALIDATEPURCHASESRESPONSE']._serialized_start=115
  _globals['_VALIDATEPURCHASESRESPONSE']._serialized_end=142
  _globals['_SCHEDULESERVICE']._serialized_start=145
  _globals['_SCHEDULESERVICE']._serialized_end=336
# @@protoc_insertion_point(module_scope)
