# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from developer.v1 import user_pb2 as developer_dot_v1_dot_user__pb2


class UserServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Get = channel.unary_unary(
                '/appsets.api.developer.v1.UserService/Get',
                request_serializer=developer_dot_v1_dot_user__pb2.GetUserRequest.SerializeToString,
                response_deserializer=developer_dot_v1_dot_user__pb2.GetUserResponse.FromString,
                _registered_method=True)
        self.Create = channel.unary_unary(
                '/appsets.api.developer.v1.UserService/Create',
                request_serializer=developer_dot_v1_dot_user__pb2.CreateUserRequest.SerializeToString,
                response_deserializer=developer_dot_v1_dot_user__pb2.CreateUserResponse.FromString,
                _registered_method=True)


class UserServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=developer_dot_v1_dot_user__pb2.GetUserRequest.FromString,
                    response_serializer=developer_dot_v1_dot_user__pb2.GetUserResponse.SerializeToString,
            ),
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=developer_dot_v1_dot_user__pb2.CreateUserRequest.FromString,
                    response_serializer=developer_dot_v1_dot_user__pb2.CreateUserResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'appsets.api.developer.v1.UserService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('appsets.api.developer.v1.UserService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/appsets.api.developer.v1.UserService/Get',
            developer_dot_v1_dot_user__pb2.GetUserRequest.SerializeToString,
            developer_dot_v1_dot_user__pb2.GetUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/appsets.api.developer.v1.UserService/Create',
            developer_dot_v1_dot_user__pb2.CreateUserRequest.SerializeToString,
            developer_dot_v1_dot_user__pb2.CreateUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
