# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from api.v1 import account_pb2 as api_dot_v1_dot_account__pb2


class AccountServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AuthenticateEmail = channel.unary_unary(
                '/appsets.api.v1.AccountService/AuthenticateEmail',
                request_serializer=api_dot_v1_dot_account__pb2.AuthenticateEmailRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_account__pb2.TokenResponse.FromString,
                _registered_method=True)
        self.RefreshToken = channel.unary_unary(
                '/appsets.api.v1.AccountService/RefreshToken',
                request_serializer=api_dot_v1_dot_account__pb2.RefreshTokenRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_account__pb2.TokenResponse.FromString,
                _registered_method=True)


class AccountServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AuthenticateEmail(self, request, context):
        """buf:lint:ignore RPC_REQUEST_RESPONSE_UNIQUE
        buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefreshToken(self, request, context):
        """buf:lint:ignore RPC_REQUEST_RESPONSE_UNIQUE
        buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AccountServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AuthenticateEmail': grpc.unary_unary_rpc_method_handler(
                    servicer.AuthenticateEmail,
                    request_deserializer=api_dot_v1_dot_account__pb2.AuthenticateEmailRequest.FromString,
                    response_serializer=api_dot_v1_dot_account__pb2.TokenResponse.SerializeToString,
            ),
            'RefreshToken': grpc.unary_unary_rpc_method_handler(
                    servicer.RefreshToken,
                    request_deserializer=api_dot_v1_dot_account__pb2.RefreshTokenRequest.FromString,
                    response_serializer=api_dot_v1_dot_account__pb2.TokenResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'appsets.api.v1.AccountService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('appsets.api.v1.AccountService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AccountService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AuthenticateEmail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/appsets.api.v1.AccountService/AuthenticateEmail',
            api_dot_v1_dot_account__pb2.AuthenticateEmailRequest.SerializeToString,
            api_dot_v1_dot_account__pb2.TokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RefreshToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/appsets.api.v1.AccountService/RefreshToken',
            api_dot_v1_dot_account__pb2.RefreshTokenRequest.SerializeToString,
            api_dot_v1_dot_account__pb2.TokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
