# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/v1/account.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'api/v1/account.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x61pi/v1/account.proto\x12\x0e\x61ppsets.api.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xb5\x01\n\x0c\x41\x63\x63ountEmail\x12\x14\n\x05\x65mail\x18\x01 \x01(\tR\x05\x65mail\x12\x1a\n\x08password\x18\x02 \x01(\tR\x08password\x12:\n\x04vars\x18\x03 \x03(\x0b\x32&.appsets.api.v1.AccountEmail.VarsEntryR\x04vars\x1a\x37\n\tVarsEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value:\x02\x38\x01\"\xa2\x01\n\x18\x41uthenticateEmailRequest\x12\x36\n\x07\x61\x63\x63ount\x18\x01 \x01(\x0b\x32\x1c.appsets.api.v1.AccountEmailR\x07\x61\x63\x63ount\x12\x32\n\x06\x63reate\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.BoolValueR\x06\x63reate\x12\x1a\n\x08username\x18\x03 \x01(\tR\x08username\"\x95\x01\n\x07Session\x12\x18\n\x07\x63reated\x18\x01 \x01(\x08R\x07\x63reated\x12\x14\n\x05token\x18\x03 \x01(\tR\x05token\x12#\n\rrefresh_token\x18\x04 \x01(\tR\x0crefreshToken\x12\x35\n\tuser_info\x18\x05 \x01(\x0b\x32\x18.appsets.api.v1.UserInfoR\x08userInfo\"\xa4\x01\n\x08UserInfo\x12\x0e\n\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n\x08username\x18\x02 \x01(\tR\x08username\x12!\n\x0c\x64isplay_name\x18\x03 \x01(\tR\x0b\x64isplayName\x12\x1d\n\navatar_url\x18\x04 \x01(\tR\tavatarUrl\x12\x14\n\x05\x65mail\x18\x05 \x01(\tR\x05\x65mail\x12\x14\n\x05phone\x18\x06 \x01(\tR\x05phone\"+\n\x13RefreshTokenRequest\x12\x14\n\x05token\x18\x01 \x01(\tR\x05token2\x8c\x02\n\x0e\x41\x63\x63ountService\x12}\n\x11\x41uthenticateEmail\x12(.appsets.api.v1.AuthenticateEmailRequest\x1a\x17.appsets.api.v1.Session\"%\x82\xd3\xe4\x93\x02\x1f\"\x1a/api/v1/authenticate/email:\x01*\x12{\n\x0cRefreshToken\x12#.appsets.api.v1.RefreshTokenRequest\x1a\x17.appsets.api.v1.Session\"-\x82\xd3\xe4\x93\x02\'\"\"/api/v1/authenticate/token/refresh:\x01*B-Z+github.com/appsets/protocol/go/api/v1;apipbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.v1.account_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z+github.com/appsets/protocol/go/api/v1;apipb'
  _globals['_ACCOUNTEMAIL_VARSENTRY']._loaded_options = None
  _globals['_ACCOUNTEMAIL_VARSENTRY']._serialized_options = b'8\001'
  _globals['_ACCOUNTSERVICE'].methods_by_name['AuthenticateEmail']._loaded_options = None
  _globals['_ACCOUNTSERVICE'].methods_by_name['AuthenticateEmail']._serialized_options = b'\202\323\344\223\002\037\"\032/api/v1/authenticate/email:\001*'
  _globals['_ACCOUNTSERVICE'].methods_by_name['RefreshToken']._loaded_options = None
  _globals['_ACCOUNTSERVICE'].methods_by_name['RefreshToken']._serialized_options = b'\202\323\344\223\002\'\"\"/api/v1/authenticate/token/refresh:\001*'
  _globals['_ACCOUNTEMAIL']._serialized_start=103
  _globals['_ACCOUNTEMAIL']._serialized_end=284
  _globals['_ACCOUNTEMAIL_VARSENTRY']._serialized_start=229
  _globals['_ACCOUNTEMAIL_VARSENTRY']._serialized_end=284
  _globals['_AUTHENTICATEEMAILREQUEST']._serialized_start=287
  _globals['_AUTHENTICATEEMAILREQUEST']._serialized_end=449
  _globals['_SESSION']._serialized_start=452
  _globals['_SESSION']._serialized_end=601
  _globals['_USERINFO']._serialized_start=604
  _globals['_USERINFO']._serialized_end=768
  _globals['_REFRESHTOKENREQUEST']._serialized_start=770
  _globals['_REFRESHTOKENREQUEST']._serialized_end=813
  _globals['_ACCOUNTSERVICE']._serialized_start=816
  _globals['_ACCOUNTSERVICE']._serialized_end=1084
# @@protoc_insertion_point(module_scope)
