# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from api.v1 import purchase_pb2 as api_dot_v1_dot_purchase__pb2


class PurchaseServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitializePurchaseAlipay = channel.unary_unary(
                '/appsets.api.v1.PurchaseService/InitializePurchaseAlipay',
                request_serializer=api_dot_v1_dot_purchase__pb2.InitializePurchaseAlipayRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_purchase__pb2.InitializePurchaseAlipayResponse.FromString,
                _registered_method=True)
        self.ValidatePurchaseAlipay = channel.unary_unary(
                '/appsets.api.v1.PurchaseService/ValidatePurchaseAlipay',
                request_serializer=api_dot_v1_dot_purchase__pb2.ValidatePurchaseAlipayRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_purchase__pb2.ValidatePurchaseAlipayResponse.FromString,
                _registered_method=True)
        self.CancelPurchase = channel.unary_unary(
                '/appsets.api.v1.PurchaseService/CancelPurchase',
                request_serializer=api_dot_v1_dot_purchase__pb2.CancelPurchaseRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_purchase__pb2.CancelPurchaseResponse.FromString,
                _registered_method=True)


class PurchaseServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def InitializePurchaseAlipay(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidatePurchaseAlipay(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelPurchase(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PurchaseServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InitializePurchaseAlipay': grpc.unary_unary_rpc_method_handler(
                    servicer.InitializePurchaseAlipay,
                    request_deserializer=api_dot_v1_dot_purchase__pb2.InitializePurchaseAlipayRequest.FromString,
                    response_serializer=api_dot_v1_dot_purchase__pb2.InitializePurchaseAlipayResponse.SerializeToString,
            ),
            'ValidatePurchaseAlipay': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidatePurchaseAlipay,
                    request_deserializer=api_dot_v1_dot_purchase__pb2.ValidatePurchaseAlipayRequest.FromString,
                    response_serializer=api_dot_v1_dot_purchase__pb2.ValidatePurchaseAlipayResponse.SerializeToString,
            ),
            'CancelPurchase': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelPurchase,
                    request_deserializer=api_dot_v1_dot_purchase__pb2.CancelPurchaseRequest.FromString,
                    response_serializer=api_dot_v1_dot_purchase__pb2.CancelPurchaseResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'appsets.api.v1.PurchaseService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('appsets.api.v1.PurchaseService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PurchaseService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InitializePurchaseAlipay(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/appsets.api.v1.PurchaseService/InitializePurchaseAlipay',
            api_dot_v1_dot_purchase__pb2.InitializePurchaseAlipayRequest.SerializeToString,
            api_dot_v1_dot_purchase__pb2.InitializePurchaseAlipayResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidatePurchaseAlipay(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/appsets.api.v1.PurchaseService/ValidatePurchaseAlipay',
            api_dot_v1_dot_purchase__pb2.ValidatePurchaseAlipayRequest.SerializeToString,
            api_dot_v1_dot_purchase__pb2.ValidatePurchaseAlipayResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelPurchase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/appsets.api.v1.PurchaseService/CancelPurchase',
            api_dot_v1_dot_purchase__pb2.CancelPurchaseRequest.SerializeToString,
            api_dot_v1_dot_purchase__pb2.CancelPurchaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
