// @generated by protoc-gen-es v2.10.0
// @generated from file developer/v1/echo.proto (package appsets.api.developer.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../google/api/annotations_pb";

/**
 * Describes the file developer/v1/echo.proto.
 */
export const file_developer_v1_echo = /*@__PURE__*/
  fileDesc("ChdkZXZlbG9wZXIvdjEvZWNoby5wcm90bxIYYXBwc2V0cy5hcGkuZGV2ZWxvcGVyLnYxIh4KDVN0cmluZ01lc3NhZ2USDQoFdmFsdWUYASABKAkygAEKC0VjaG9TZXJ2aWNlEnEKBEVjaG8SJy5hcHBzZXRzLmFwaS5kZXZlbG9wZXIudjEuU3RyaW5nTWVzc2FnZRonLmFwcHNldHMuYXBpLmRldmVsb3Blci52MS5TdHJpbmdNZXNzYWdlIheC0+STAhE6ASoiDC9hcGkvdjEvZWNob0I5WjdnaXRodWIuY29tL2FwcHNldHMvcHJvdG9jb2wvZ28vZGV2ZWxvcGVyL3YxO2RldmVsb3BlcnBiYgZwcm90bzM", [file_google_api_annotations]);

/**
 * Describes the message appsets.api.developer.v1.StringMessage.
 * Use `create(StringMessageSchema)` to create a new message.
 */
export const StringMessageSchema = /*@__PURE__*/
  messageDesc(file_developer_v1_echo, 0);

/**
 * @generated from service appsets.api.developer.v1.EchoService
 */
export const EchoService = /*@__PURE__*/
  serviceDesc(file_developer_v1_echo, 0);

