// @generated by protoc-gen-es v2.10.0
// @generated from file developer/v1/organization.proto (package appsets.api.developer.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../google/api/annotations_pb";

/**
 * Describes the file developer/v1/organization.proto.
 */
export const file_developer_v1_organization = /*@__PURE__*/
  fileDesc("Ch9kZXZlbG9wZXIvdjEvb3JnYW5pemF0aW9uLnByb3RvEhhhcHBzZXRzLmFwaS5kZXZlbG9wZXIudjEiaQoZQ3JlYXRlT3JnYW5pemF0aW9uUmVxdWVzdBIKCgJpZBgBIAEoCRIMCgRjb2RlGAIgASgJEgwKBG5hbWUYAyABKAkSEAoIb3duZWRfYnkYBCABKAkSEgoKY3JlYXRlZF9ieRgFIAEoCSIcChpDcmVhdGVPcmdhbml6YXRpb25SZXNwb25zZTKzAQoTT3JnYW5pemF0aW9uU2VydmljZRKbAQoGQ3JlYXRlEjMuYXBwc2V0cy5hcGkuZGV2ZWxvcGVyLnYxLkNyZWF0ZU9yZ2FuaXphdGlvblJlcXVlc3QaNC5hcHBzZXRzLmFwaS5kZXZlbG9wZXIudjEuQ3JlYXRlT3JnYW5pemF0aW9uUmVzcG9uc2UiJoLT5JMCIDoBKiIbL2FwaS92MS9vcmdhbml6YXRpb24vY3JlYXRlQjlaN2dpdGh1Yi5jb20vYXBwc2V0cy9wcm90b2NvbC9nby9kZXZlbG9wZXIvdjE7ZGV2ZWxvcGVycGJiBnByb3RvMw", [file_google_api_annotations]);

/**
 * Describes the message appsets.api.developer.v1.CreateOrganizationRequest.
 * Use `create(CreateOrganizationRequestSchema)` to create a new message.
 */
export const CreateOrganizationRequestSchema = /*@__PURE__*/
  messageDesc(file_developer_v1_organization, 0);

/**
 * Describes the message appsets.api.developer.v1.CreateOrganizationResponse.
 * Use `create(CreateOrganizationResponseSchema)` to create a new message.
 */
export const CreateOrganizationResponseSchema = /*@__PURE__*/
  messageDesc(file_developer_v1_organization, 1);

/**
 * @generated from service appsets.api.developer.v1.OrganizationService
 */
export const OrganizationService = /*@__PURE__*/
  serviceDesc(file_developer_v1_organization, 0);

