// @generated by protoc-gen-es v2.10.0
// @generated from file developer/v1/schedule.proto (package appsets.api.developer.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file developer/v1/schedule.proto.
 */
export declare const file_developer_v1_schedule: GenFile;

/**
 * @generated from message appsets.api.developer.v1.ValidatePurchasesRequest
 */
export declare type ValidatePurchasesRequest = Message<"appsets.api.developer.v1.ValidatePurchasesRequest"> & {
};

/**
 * Describes the message appsets.api.developer.v1.ValidatePurchasesRequest.
 * Use `create(ValidatePurchasesRequestSchema)` to create a new message.
 */
export declare const ValidatePurchasesRequestSchema: GenMessage<ValidatePurchasesRequest>;

/**
 * @generated from message appsets.api.developer.v1.ValidatePurchasesResponse
 */
export declare type ValidatePurchasesResponse = Message<"appsets.api.developer.v1.ValidatePurchasesResponse"> & {
};

/**
 * Describes the message appsets.api.developer.v1.ValidatePurchasesResponse.
 * Use `create(ValidatePurchasesResponseSchema)` to create a new message.
 */
export declare const ValidatePurchasesResponseSchema: GenMessage<ValidatePurchasesResponse>;

/**
 * @generated from service appsets.api.developer.v1.ScheduleService
 */
export declare const ScheduleService: GenService<{
  /**
   * @generated from rpc appsets.api.developer.v1.ScheduleService.ValidatePurchases
   */
  validatePurchases: {
    methodKind: "unary";
    input: typeof ValidatePurchasesRequestSchema;
    output: typeof ValidatePurchasesResponseSchema;
  },
}>;

