// @generated by protoc-gen-es v2.10.0
// @generated from file developer/v1/schedule.proto (package appsets.api.developer.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../google/api/annotations_pb";

/**
 * Describes the file developer/v1/schedule.proto.
 */
export const file_developer_v1_schedule = /*@__PURE__*/
  fileDesc("ChtkZXZlbG9wZXIvdjEvc2NoZWR1bGUucHJvdG8SGGFwcHNldHMuYXBpLmRldmVsb3Blci52MSIaChhWYWxpZGF0ZVB1cmNoYXNlc1JlcXVlc3QiGwoZVmFsaWRhdGVQdXJjaGFzZXNSZXNwb25zZTK/AQoPU2NoZWR1bGVTZXJ2aWNlEqsBChFWYWxpZGF0ZVB1cmNoYXNlcxIyLmFwcHNldHMuYXBpLmRldmVsb3Blci52MS5WYWxpZGF0ZVB1cmNoYXNlc1JlcXVlc3QaMy5hcHBzZXRzLmFwaS5kZXZlbG9wZXIudjEuVmFsaWRhdGVQdXJjaGFzZXNSZXNwb25zZSItgtPkkwInOgEqIiIvYXBpL3YxL3NjaGVkdWxlL3B1cmNoYXNlL3ZhbGlkYXRlQjlaN2dpdGh1Yi5jb20vYXBwc2V0cy9wcm90b2NvbC9nby9kZXZlbG9wZXIvdjE7ZGV2ZWxvcGVycGJiBnByb3RvMw", [file_google_api_annotations]);

/**
 * Describes the message appsets.api.developer.v1.ValidatePurchasesRequest.
 * Use `create(ValidatePurchasesRequestSchema)` to create a new message.
 */
export const ValidatePurchasesRequestSchema = /*@__PURE__*/
  messageDesc(file_developer_v1_schedule, 0);

/**
 * Describes the message appsets.api.developer.v1.ValidatePurchasesResponse.
 * Use `create(ValidatePurchasesResponseSchema)` to create a new message.
 */
export const ValidatePurchasesResponseSchema = /*@__PURE__*/
  messageDesc(file_developer_v1_schedule, 1);

/**
 * @generated from service appsets.api.developer.v1.ScheduleService
 */
export const ScheduleService = /*@__PURE__*/
  serviceDesc(file_developer_v1_schedule, 0);

