// @generated by protoc-gen-es v2.10.0
// @generated from file developer/v1/user.proto (package appsets.api.developer.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file developer/v1/user.proto.
 */
export declare const file_developer_v1_user: GenFile;

/**
 * @generated from message appsets.api.developer.v1.GetUserRequest
 */
export declare type GetUserRequest = Message<"appsets.api.developer.v1.GetUserRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message appsets.api.developer.v1.GetUserRequest.
 * Use `create(GetUserRequestSchema)` to create a new message.
 */
export declare const GetUserRequestSchema: GenMessage<GetUserRequest>;

/**
 * @generated from message appsets.api.developer.v1.GetUserResponse
 */
export declare type GetUserResponse = Message<"appsets.api.developer.v1.GetUserResponse"> & {
};

/**
 * Describes the message appsets.api.developer.v1.GetUserResponse.
 * Use `create(GetUserResponseSchema)` to create a new message.
 */
export declare const GetUserResponseSchema: GenMessage<GetUserResponse>;

/**
 * @generated from message appsets.api.developer.v1.CreateUserRequest
 */
export declare type CreateUserRequest = Message<"appsets.api.developer.v1.CreateUserRequest"> & {
};

/**
 * Describes the message appsets.api.developer.v1.CreateUserRequest.
 * Use `create(CreateUserRequestSchema)` to create a new message.
 */
export declare const CreateUserRequestSchema: GenMessage<CreateUserRequest>;

/**
 * @generated from message appsets.api.developer.v1.CreateUserResponse
 */
export declare type CreateUserResponse = Message<"appsets.api.developer.v1.CreateUserResponse"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string code = 2;
   */
  code: string;

  /**
   * @generated from field: string display_name = 3;
   */
  displayName: string;

  /**
   * @generated from field: string email = 4;
   */
  email: string;

  /**
   * @generated from field: string phone = 5;
   */
  phone: string;
};

/**
 * Describes the message appsets.api.developer.v1.CreateUserResponse.
 * Use `create(CreateUserResponseSchema)` to create a new message.
 */
export declare const CreateUserResponseSchema: GenMessage<CreateUserResponse>;

/**
 * @generated from enum appsets.api.developer.v1.UserRole
 */
export enum UserRole {
  /**
   * @generated from enum value: USER_ROLE_UNKNOWN = 0;
   */
  UNKNOWN = 0,

  /**
   * All access
   *
   * @generated from enum value: USER_ROLE_ADMIN = 1;
   */
  ADMIN = 1,

  /**
   * Best for developers, also enables APIs and API explorer
   *
   * @generated from enum value: USER_ROLE_DEVELOPER = 2;
   */
  DEVELOPER = 2,

  /**
   * Best for users who regularly update player information.
   *
   * @generated from enum value: USER_ROLE_MAINTAINER = 3;
   */
  MAINTAINER = 3,

  /**
   * Read-only role for those only need to view data
   *
   * @generated from enum value: USER_ROLE_READONLY = 4;
   */
  READONLY = 4,
}

/**
 * Describes the enum appsets.api.developer.v1.UserRole.
 */
export declare const UserRoleSchema: GenEnum<UserRole>;

/**
 * @generated from service appsets.api.developer.v1.UserService
 */
export declare const UserService: GenService<{
  /**
   * @generated from rpc appsets.api.developer.v1.UserService.Get
   */
  get: {
    methodKind: "unary";
    input: typeof GetUserRequestSchema;
    output: typeof GetUserResponseSchema;
  },
  /**
   * @generated from rpc appsets.api.developer.v1.UserService.Create
   */
  create: {
    methodKind: "unary";
    input: typeof CreateUserRequestSchema;
    output: typeof CreateUserResponseSchema;
  },
}>;

