// @generated by protoc-gen-es v2.10.0
// @generated from file developer/v1/user.proto (package appsets.api.developer.v1, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, serviceDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../google/api/annotations_pb";

/**
 * Describes the file developer/v1/user.proto.
 */
export const file_developer_v1_user = /*@__PURE__*/
  fileDesc("ChdkZXZlbG9wZXIvdjEvdXNlci5wcm90bxIYYXBwc2V0cy5hcGkuZGV2ZWxvcGVyLnYxIh4KDkdldFVzZXJSZXF1ZXN0EgwKBG5hbWUYASABKAkiEQoPR2V0VXNlclJlc3BvbnNlIhMKEUNyZWF0ZVVzZXJSZXF1ZXN0ImIKEkNyZWF0ZVVzZXJSZXNwb25zZRIKCgJpZBgBIAEoCRIMCgRjb2RlGAIgASgJEhQKDGRpc3BsYXlfbmFtZRgDIAEoCRINCgVlbWFpbBgEIAEoCRINCgVwaG9uZRgFIAEoCSqBAQoIVXNlclJvbGUSFQoRVVNFUl9ST0xFX1VOS05PV04QABITCg9VU0VSX1JPTEVfQURNSU4QARIXChNVU0VSX1JPTEVfREVWRUxPUEVSEAISGAoUVVNFUl9ST0xFX01BSU5UQUlORVIQAxIWChJVU0VSX1JPTEVfUkVBRE9OTFkQBDKOAgoLVXNlclNlcnZpY2USeAoDR2V0EiguYXBwc2V0cy5hcGkuZGV2ZWxvcGVyLnYxLkdldFVzZXJSZXF1ZXN0GikuYXBwc2V0cy5hcGkuZGV2ZWxvcGVyLnYxLkdldFVzZXJSZXNwb25zZSIcgtPkkwIWOgEqIhEvYXBpL3YxL3VzZXJzL2dldBKEAQoGQ3JlYXRlEisuYXBwc2V0cy5hcGkuZGV2ZWxvcGVyLnYxLkNyZWF0ZVVzZXJSZXF1ZXN0GiwuYXBwc2V0cy5hcGkuZGV2ZWxvcGVyLnYxLkNyZWF0ZVVzZXJSZXNwb25zZSIfgtPkkwIZOgEqIhQvYXBpL3YxL3VzZXJzL2NyZWF0ZUI5WjdnaXRodWIuY29tL2FwcHNldHMvcHJvdG9jb2wvZ28vZGV2ZWxvcGVyL3YxO2RldmVsb3BlcnBiYgZwcm90bzM", [file_google_api_annotations]);

/**
 * Describes the message appsets.api.developer.v1.GetUserRequest.
 * Use `create(GetUserRequestSchema)` to create a new message.
 */
export const GetUserRequestSchema = /*@__PURE__*/
  messageDesc(file_developer_v1_user, 0);

/**
 * Describes the message appsets.api.developer.v1.GetUserResponse.
 * Use `create(GetUserResponseSchema)` to create a new message.
 */
export const GetUserResponseSchema = /*@__PURE__*/
  messageDesc(file_developer_v1_user, 1);

/**
 * Describes the message appsets.api.developer.v1.CreateUserRequest.
 * Use `create(CreateUserRequestSchema)` to create a new message.
 */
export const CreateUserRequestSchema = /*@__PURE__*/
  messageDesc(file_developer_v1_user, 2);

/**
 * Describes the message appsets.api.developer.v1.CreateUserResponse.
 * Use `create(CreateUserResponseSchema)` to create a new message.
 */
export const CreateUserResponseSchema = /*@__PURE__*/
  messageDesc(file_developer_v1_user, 3);

/**
 * Describes the enum appsets.api.developer.v1.UserRole.
 */
export const UserRoleSchema = /*@__PURE__*/
  enumDesc(file_developer_v1_user, 0);

/**
 * @generated from enum appsets.api.developer.v1.UserRole
 */
export const UserRole = /*@__PURE__*/
  tsEnum(UserRoleSchema);

/**
 * @generated from service appsets.api.developer.v1.UserService
 */
export const UserService = /*@__PURE__*/
  serviceDesc(file_developer_v1_user, 0);

