// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: openapi/v1/organization.proto

// buf:lint:ignore PACKAGE_DIRECTORY_MATCH

package openapipb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	status "google.golang.org/genproto/googleapis/rpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateOrganizationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	OwnedBy       string                 `protobuf:"bytes,4,opt,name=owned_by,json=ownedBy,proto3" json:"owned_by,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,5,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrganizationRequest) Reset() {
	*x = CreateOrganizationRequest{}
	mi := &file_openapi_v1_organization_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrganizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrganizationRequest) ProtoMessage() {}

func (x *CreateOrganizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openapi_v1_organization_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrganizationRequest.ProtoReflect.Descriptor instead.
func (*CreateOrganizationRequest) Descriptor() ([]byte, []int) {
	return file_openapi_v1_organization_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOrganizationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateOrganizationRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateOrganizationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateOrganizationRequest) GetOwnedBy() string {
	if x != nil {
		return x.OwnedBy
	}
	return ""
}

func (x *CreateOrganizationRequest) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

type CreateOrganizationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *status.Status         `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrganizationResponse) Reset() {
	*x = CreateOrganizationResponse{}
	mi := &file_openapi_v1_organization_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrganizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrganizationResponse) ProtoMessage() {}

func (x *CreateOrganizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openapi_v1_organization_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrganizationResponse.ProtoReflect.Descriptor instead.
func (*CreateOrganizationResponse) Descriptor() ([]byte, []int) {
	return file_openapi_v1_organization_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOrganizationResponse) GetError() *status.Status {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_openapi_v1_organization_proto protoreflect.FileDescriptor

const file_openapi_v1_organization_proto_rawDesc = "" +
	"\n" +
	"\x1dopenapi/v1/organization.proto\x12\x12appsets.openapi.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/rpc/status.proto\"\x8d\x01\n" +
	"\x19CreateOrganizationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x19\n" +
	"\bowned_by\x18\x04 \x01(\tR\aownedBy\x12\x1d\n" +
	"\n" +
	"created_by\x18\x05 \x01(\tR\tcreatedBy\"F\n" +
	"\x1aCreateOrganizationResponse\x12(\n" +
	"\x05error\x18\x01 \x01(\v2\x12.google.rpc.StatusR\x05error2\xb3\x01\n" +
	"\x13OrganizationService\x12\x9b\x01\n" +
	"\x12CreateOrganization\x12-.appsets.openapi.v1.CreateOrganizationRequest\x1a..appsets.openapi.v1.CreateOrganizationResponse\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/api/v1/organization/createB5Z3github.com/appsets/protocol/go/openapi/v1;openapipbb\x06proto3"

var (
	file_openapi_v1_organization_proto_rawDescOnce sync.Once
	file_openapi_v1_organization_proto_rawDescData []byte
)

func file_openapi_v1_organization_proto_rawDescGZIP() []byte {
	file_openapi_v1_organization_proto_rawDescOnce.Do(func() {
		file_openapi_v1_organization_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openapi_v1_organization_proto_rawDesc), len(file_openapi_v1_organization_proto_rawDesc)))
	})
	return file_openapi_v1_organization_proto_rawDescData
}

var file_openapi_v1_organization_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_openapi_v1_organization_proto_goTypes = []any{
	(*CreateOrganizationRequest)(nil),  // 0: appsets.openapi.v1.CreateOrganizationRequest
	(*CreateOrganizationResponse)(nil), // 1: appsets.openapi.v1.CreateOrganizationResponse
	(*status.Status)(nil),              // 2: google.rpc.Status
}
var file_openapi_v1_organization_proto_depIdxs = []int32{
	2, // 0: appsets.openapi.v1.CreateOrganizationResponse.error:type_name -> google.rpc.Status
	0, // 1: appsets.openapi.v1.OrganizationService.CreateOrganization:input_type -> appsets.openapi.v1.CreateOrganizationRequest
	1, // 2: appsets.openapi.v1.OrganizationService.CreateOrganization:output_type -> appsets.openapi.v1.CreateOrganizationResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_openapi_v1_organization_proto_init() }
func file_openapi_v1_organization_proto_init() {
	if File_openapi_v1_organization_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openapi_v1_organization_proto_rawDesc), len(file_openapi_v1_organization_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_openapi_v1_organization_proto_goTypes,
		DependencyIndexes: file_openapi_v1_organization_proto_depIdxs,
		MessageInfos:      file_openapi_v1_organization_proto_msgTypes,
	}.Build()
	File_openapi_v1_organization_proto = out.File
	file_openapi_v1_organization_proto_goTypes = nil
	file_openapi_v1_organization_proto_depIdxs = nil
}
