// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: openapi/v1/schedule.proto

package openapipb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidatePurchasesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidatePurchasesRequest) Reset() {
	*x = ValidatePurchasesRequest{}
	mi := &file_openapi_v1_schedule_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatePurchasesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatePurchasesRequest) ProtoMessage() {}

func (x *ValidatePurchasesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openapi_v1_schedule_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatePurchasesRequest.ProtoReflect.Descriptor instead.
func (*ValidatePurchasesRequest) Descriptor() ([]byte, []int) {
	return file_openapi_v1_schedule_proto_rawDescGZIP(), []int{0}
}

type ValidatePurchasesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidatePurchasesResponse) Reset() {
	*x = ValidatePurchasesResponse{}
	mi := &file_openapi_v1_schedule_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatePurchasesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatePurchasesResponse) ProtoMessage() {}

func (x *ValidatePurchasesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openapi_v1_schedule_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatePurchasesResponse.ProtoReflect.Descriptor instead.
func (*ValidatePurchasesResponse) Descriptor() ([]byte, []int) {
	return file_openapi_v1_schedule_proto_rawDescGZIP(), []int{1}
}

var File_openapi_v1_schedule_proto protoreflect.FileDescriptor

const file_openapi_v1_schedule_proto_rawDesc = "" +
	"\n" +
	"\x19openapi/v1/schedule.proto\x12\x12appsets.openapi.v1\x1a\x1cgoogle/api/annotations.proto\"\x1a\n" +
	"\x18ValidatePurchasesRequest\"\x1b\n" +
	"\x19ValidatePurchasesResponse2\xb3\x01\n" +
	"\x0fScheduleService\x12\x9f\x01\n" +
	"\x11ValidatePurchases\x12,.appsets.openapi.v1.ValidatePurchasesRequest\x1a-.appsets.openapi.v1.ValidatePurchasesResponse\"-\x82\xd3\xe4\x93\x02':\x01*\"\"/api/v1/schedule/purchase/validateB5Z3github.com/appsets/protocol/go/openapi/v1;openapipbb\x06proto3"

var (
	file_openapi_v1_schedule_proto_rawDescOnce sync.Once
	file_openapi_v1_schedule_proto_rawDescData []byte
)

func file_openapi_v1_schedule_proto_rawDescGZIP() []byte {
	file_openapi_v1_schedule_proto_rawDescOnce.Do(func() {
		file_openapi_v1_schedule_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openapi_v1_schedule_proto_rawDesc), len(file_openapi_v1_schedule_proto_rawDesc)))
	})
	return file_openapi_v1_schedule_proto_rawDescData
}

var file_openapi_v1_schedule_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_openapi_v1_schedule_proto_goTypes = []any{
	(*ValidatePurchasesRequest)(nil),  // 0: appsets.openapi.v1.ValidatePurchasesRequest
	(*ValidatePurchasesResponse)(nil), // 1: appsets.openapi.v1.ValidatePurchasesResponse
}
var file_openapi_v1_schedule_proto_depIdxs = []int32{
	0, // 0: appsets.openapi.v1.ScheduleService.ValidatePurchases:input_type -> appsets.openapi.v1.ValidatePurchasesRequest
	1, // 1: appsets.openapi.v1.ScheduleService.ValidatePurchases:output_type -> appsets.openapi.v1.ValidatePurchasesResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_openapi_v1_schedule_proto_init() }
func file_openapi_v1_schedule_proto_init() {
	if File_openapi_v1_schedule_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openapi_v1_schedule_proto_rawDesc), len(file_openapi_v1_schedule_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_openapi_v1_schedule_proto_goTypes,
		DependencyIndexes: file_openapi_v1_schedule_proto_depIdxs,
		MessageInfos:      file_openapi_v1_schedule_proto_msgTypes,
	}.Build()
	File_openapi_v1_schedule_proto = out.File
	file_openapi_v1_schedule_proto_goTypes = nil
	file_openapi_v1_schedule_proto_depIdxs = nil
}
