// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: openapi/v1/user.proto

// buf:lint:ignore PACKAGE_DIRECTORY_MATCH

package openapipb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	status "google.golang.org/genproto/googleapis/rpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserRole int32

const (
	UserRole_USER_ROLE_UNSPECIFIED UserRole = 0
	UserRole_USER_ROLE_ADMIN       UserRole = 1 // All access
	UserRole_USER_ROLE_DEVELOPER   UserRole = 2 // Best for developers, also enables APIs and API explorer
	UserRole_USER_ROLE_MAINTAINER  UserRole = 3 // Best for users who regularly update player information.
	UserRole_USER_ROLE_READONLY    UserRole = 4 // Read-only role for those only need to view data
)

// Enum value maps for UserRole.
var (
	UserRole_name = map[int32]string{
		0: "USER_ROLE_UNSPECIFIED",
		1: "USER_ROLE_ADMIN",
		2: "USER_ROLE_DEVELOPER",
		3: "USER_ROLE_MAINTAINER",
		4: "USER_ROLE_READONLY",
	}
	UserRole_value = map[string]int32{
		"USER_ROLE_UNSPECIFIED": 0,
		"USER_ROLE_ADMIN":       1,
		"USER_ROLE_DEVELOPER":   2,
		"USER_ROLE_MAINTAINER":  3,
		"USER_ROLE_READONLY":    4,
	}
)

func (x UserRole) Enum() *UserRole {
	p := new(UserRole)
	*p = x
	return p
}

func (x UserRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserRole) Descriptor() protoreflect.EnumDescriptor {
	return file_openapi_v1_user_proto_enumTypes[0].Descriptor()
}

func (UserRole) Type() protoreflect.EnumType {
	return &file_openapi_v1_user_proto_enumTypes[0]
}

func (x UserRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserRole.Descriptor instead.
func (UserRole) EnumDescriptor() ([]byte, []int) {
	return file_openapi_v1_user_proto_rawDescGZIP(), []int{0}
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_openapi_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openapi_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_openapi_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *status.Status         `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_openapi_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openapi_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_openapi_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserResponse) GetError() *status.Status {
	if x != nil {
		return x.Error
	}
	return nil
}

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_openapi_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openapi_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_openapi_v1_user_proto_rawDescGZIP(), []int{2}
}

type CreateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *status.Status         `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	DisplayName   string                 `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Email         string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_openapi_v1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openapi_v1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_openapi_v1_user_proto_rawDescGZIP(), []int{3}
}

func (x *CreateUserResponse) GetError() *status.Status {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *CreateUserResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateUserResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateUserResponse) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *CreateUserResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserResponse) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

var File_openapi_v1_user_proto protoreflect.FileDescriptor

const file_openapi_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x15openapi/v1/user.proto\x12\x12appsets.openapi.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/rpc/status.proto\"$\n" +
	"\x0eGetUserRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\";\n" +
	"\x0fGetUserResponse\x12(\n" +
	"\x05error\x18\x01 \x01(\v2\x12.google.rpc.StatusR\x05error\"\x13\n" +
	"\x11CreateUserRequest\"\xb1\x01\n" +
	"\x12CreateUserResponse\x12(\n" +
	"\x05error\x18\x01 \x01(\v2\x12.google.rpc.StatusR\x05error\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12!\n" +
	"\fdisplay_name\x18\x04 \x01(\tR\vdisplayName\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x06 \x01(\tR\x05phone*\x85\x01\n" +
	"\bUserRole\x12\x19\n" +
	"\x15USER_ROLE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fUSER_ROLE_ADMIN\x10\x01\x12\x17\n" +
	"\x13USER_ROLE_DEVELOPER\x10\x02\x12\x18\n" +
	"\x14USER_ROLE_MAINTAINER\x10\x03\x12\x16\n" +
	"\x12USER_ROLE_READONLY\x10\x042\xfd\x01\n" +
	"\vUserService\x12p\n" +
	"\aGetUser\x12\".appsets.openapi.v1.GetUserRequest\x1a#.appsets.openapi.v1.GetUserResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/api/v1/users/get\x12|\n" +
	"\n" +
	"CreateUser\x12%.appsets.openapi.v1.CreateUserRequest\x1a&.appsets.openapi.v1.CreateUserResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/api/v1/users/createB5Z3github.com/appsets/protocol/go/openapi/v1;openapipbb\x06proto3"

var (
	file_openapi_v1_user_proto_rawDescOnce sync.Once
	file_openapi_v1_user_proto_rawDescData []byte
)

func file_openapi_v1_user_proto_rawDescGZIP() []byte {
	file_openapi_v1_user_proto_rawDescOnce.Do(func() {
		file_openapi_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openapi_v1_user_proto_rawDesc), len(file_openapi_v1_user_proto_rawDesc)))
	})
	return file_openapi_v1_user_proto_rawDescData
}

var file_openapi_v1_user_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_openapi_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_openapi_v1_user_proto_goTypes = []any{
	(UserRole)(0),              // 0: appsets.openapi.v1.UserRole
	(*GetUserRequest)(nil),     // 1: appsets.openapi.v1.GetUserRequest
	(*GetUserResponse)(nil),    // 2: appsets.openapi.v1.GetUserResponse
	(*CreateUserRequest)(nil),  // 3: appsets.openapi.v1.CreateUserRequest
	(*CreateUserResponse)(nil), // 4: appsets.openapi.v1.CreateUserResponse
	(*status.Status)(nil),      // 5: google.rpc.Status
}
var file_openapi_v1_user_proto_depIdxs = []int32{
	5, // 0: appsets.openapi.v1.GetUserResponse.error:type_name -> google.rpc.Status
	5, // 1: appsets.openapi.v1.CreateUserResponse.error:type_name -> google.rpc.Status
	1, // 2: appsets.openapi.v1.UserService.GetUser:input_type -> appsets.openapi.v1.GetUserRequest
	3, // 3: appsets.openapi.v1.UserService.CreateUser:input_type -> appsets.openapi.v1.CreateUserRequest
	2, // 4: appsets.openapi.v1.UserService.GetUser:output_type -> appsets.openapi.v1.GetUserResponse
	4, // 5: appsets.openapi.v1.UserService.CreateUser:output_type -> appsets.openapi.v1.CreateUserResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_openapi_v1_user_proto_init() }
func file_openapi_v1_user_proto_init() {
	if File_openapi_v1_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openapi_v1_user_proto_rawDesc), len(file_openapi_v1_user_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_openapi_v1_user_proto_goTypes,
		DependencyIndexes: file_openapi_v1_user_proto_depIdxs,
		EnumInfos:         file_openapi_v1_user_proto_enumTypes,
		MessageInfos:      file_openapi_v1_user_proto_msgTypes,
	}.Build()
	File_openapi_v1_user_proto = out.File
	file_openapi_v1_user_proto_goTypes = nil
	file_openapi_v1_user_proto_depIdxs = nil
}
