// @generated by protoc-gen-es v2.10.0
// @generated from file api/v1/account.proto (package appsets.api.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../google/api/annotations_pb";
import { file_google_protobuf_wrappers } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file api/v1/account.proto.
 */
export const file_api_v1_account = /*@__PURE__*/
  fileDesc("ChRhcGkvdjEvYWNjb3VudC5wcm90bxIOYXBwc2V0cy5hcGkudjEikgEKDEFjY291bnRFbWFpbBINCgVlbWFpbBgBIAEoCRIQCghwYXNzd29yZBgCIAEoCRI0CgR2YXJzGAMgAygLMiYuYXBwc2V0cy5hcGkudjEuQWNjb3VudEVtYWlsLlZhcnNFbnRyeRorCglWYXJzRW50cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgJOgI4ASKHAQoYQXV0aGVudGljYXRlRW1haWxSZXF1ZXN0Ei0KB2FjY291bnQYASABKAsyHC5hcHBzZXRzLmFwaS52MS5BY2NvdW50RW1haWwSKgoGY3JlYXRlGAIgASgLMhouZ29vZ2xlLnByb3RvYnVmLkJvb2xWYWx1ZRIQCgh1c2VybmFtZRgDIAEoCSJtCgdTZXNzaW9uEg8KB2NyZWF0ZWQYASABKAgSDQoFdG9rZW4YAyABKAkSFQoNcmVmcmVzaF90b2tlbhgEIAEoCRIrCgl1c2VyX2luZm8YBSABKAsyGC5hcHBzZXRzLmFwaS52MS5Vc2VySW5mbyJwCghVc2VySW5mbxIKCgJpZBgBIAEoAxIQCgh1c2VybmFtZRgCIAEoCRIUCgxkaXNwbGF5X25hbWUYAyABKAkSEgoKYXZhdGFyX3VybBgEIAEoCRINCgVlbWFpbBgFIAEoCRINCgVwaG9uZRgGIAEoCSIkChNSZWZyZXNoVG9rZW5SZXF1ZXN0Eg0KBXRva2VuGAEgASgJMowCCg5BY2NvdW50U2VydmljZRJ9ChFBdXRoZW50aWNhdGVFbWFpbBIoLmFwcHNldHMuYXBpLnYxLkF1dGhlbnRpY2F0ZUVtYWlsUmVxdWVzdBoXLmFwcHNldHMuYXBpLnYxLlNlc3Npb24iJYLT5JMCHzoBKiIaL2FwaS92MS9hdXRoZW50aWNhdGUvZW1haWwSewoMUmVmcmVzaFRva2VuEiMuYXBwc2V0cy5hcGkudjEuUmVmcmVzaFRva2VuUmVxdWVzdBoXLmFwcHNldHMuYXBpLnYxLlNlc3Npb24iLYLT5JMCJzoBKiIiL2FwaS92MS9hdXRoZW50aWNhdGUvdG9rZW4vcmVmcmVzaEItWitnaXRodWIuY29tL2FwcHNldHMvcHJvdG9jb2wvZ28vYXBpL3YxO2FwaXBiYgZwcm90bzM", [file_google_api_annotations, file_google_protobuf_wrappers]);

/**
 * Describes the message appsets.api.v1.AccountEmail.
 * Use `create(AccountEmailSchema)` to create a new message.
 */
export const AccountEmailSchema = /*@__PURE__*/
  messageDesc(file_api_v1_account, 0);

/**
 * Describes the message appsets.api.v1.AuthenticateEmailRequest.
 * Use `create(AuthenticateEmailRequestSchema)` to create a new message.
 */
export const AuthenticateEmailRequestSchema = /*@__PURE__*/
  messageDesc(file_api_v1_account, 1);

/**
 * Describes the message appsets.api.v1.Session.
 * Use `create(SessionSchema)` to create a new message.
 */
export const SessionSchema = /*@__PURE__*/
  messageDesc(file_api_v1_account, 2);

/**
 * Describes the message appsets.api.v1.UserInfo.
 * Use `create(UserInfoSchema)` to create a new message.
 */
export const UserInfoSchema = /*@__PURE__*/
  messageDesc(file_api_v1_account, 3);

/**
 * Describes the message appsets.api.v1.RefreshTokenRequest.
 * Use `create(RefreshTokenRequestSchema)` to create a new message.
 */
export const RefreshTokenRequestSchema = /*@__PURE__*/
  messageDesc(file_api_v1_account, 4);

/**
 * @generated from service appsets.api.v1.AccountService
 */
export const AccountService = /*@__PURE__*/
  serviceDesc(file_api_v1_account, 0);

