// @generated by protoc-gen-es v2.10.0
// @generated from file api/v1/account.proto (package appsets.api.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/v1/account.proto.
 */
export declare const file_api_v1_account: GenFile;

/**
 * @generated from message appsets.api.v1.AccountEmail
 */
export declare type AccountEmail = Message<"appsets.api.v1.AccountEmail"> & {
  /**
   * @generated from field: string email = 1;
   */
  email: string;

  /**
   * @generated from field: string password = 2;
   */
  password: string;

  /**
   * @generated from field: map<string, string> vars = 3;
   */
  vars: { [key: string]: string };
};

/**
 * Describes the message appsets.api.v1.AccountEmail.
 * Use `create(AccountEmailSchema)` to create a new message.
 */
export declare const AccountEmailSchema: GenMessage<AccountEmail>;

/**
 * @generated from message appsets.api.v1.AuthenticateEmailRequest
 */
export declare type AuthenticateEmailRequest = Message<"appsets.api.v1.AuthenticateEmailRequest"> & {
  /**
   * @generated from field: appsets.api.v1.AccountEmail account = 1;
   */
  account?: AccountEmail;

  /**
   * @generated from field: google.protobuf.BoolValue create = 2;
   */
  create?: boolean;

  /**
   * @generated from field: string username = 3;
   */
  username: string;
};

/**
 * Describes the message appsets.api.v1.AuthenticateEmailRequest.
 * Use `create(AuthenticateEmailRequestSchema)` to create a new message.
 */
export declare const AuthenticateEmailRequestSchema: GenMessage<AuthenticateEmailRequest>;

/**
 * @generated from message appsets.api.v1.Session
 */
export declare type Session = Message<"appsets.api.v1.Session"> & {
  /**
   * @generated from field: bool created = 1;
   */
  created: boolean;

  /**
   * @generated from field: string token = 3;
   */
  token: string;

  /**
   * @generated from field: string refresh_token = 4;
   */
  refreshToken: string;

  /**
   * @generated from field: appsets.api.v1.UserInfo user_info = 5;
   */
  userInfo?: UserInfo;
};

/**
 * Describes the message appsets.api.v1.Session.
 * Use `create(SessionSchema)` to create a new message.
 */
export declare const SessionSchema: GenMessage<Session>;

/**
 * @generated from message appsets.api.v1.UserInfo
 */
export declare type UserInfo = Message<"appsets.api.v1.UserInfo"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: string username = 2;
   */
  username: string;

  /**
   * @generated from field: string display_name = 3;
   */
  displayName: string;

  /**
   * @generated from field: string avatar_url = 4;
   */
  avatarUrl: string;

  /**
   * @generated from field: string email = 5;
   */
  email: string;

  /**
   * @generated from field: string phone = 6;
   */
  phone: string;
};

/**
 * Describes the message appsets.api.v1.UserInfo.
 * Use `create(UserInfoSchema)` to create a new message.
 */
export declare const UserInfoSchema: GenMessage<UserInfo>;

/**
 * @generated from message appsets.api.v1.RefreshTokenRequest
 */
export declare type RefreshTokenRequest = Message<"appsets.api.v1.RefreshTokenRequest"> & {
  /**
   * @generated from field: string token = 1;
   */
  token: string;
};

/**
 * Describes the message appsets.api.v1.RefreshTokenRequest.
 * Use `create(RefreshTokenRequestSchema)` to create a new message.
 */
export declare const RefreshTokenRequestSchema: GenMessage<RefreshTokenRequest>;

/**
 * @generated from service appsets.api.v1.AccountService
 */
export declare const AccountService: GenService<{
  /**
   * @generated from rpc appsets.api.v1.AccountService.AuthenticateEmail
   */
  authenticateEmail: {
    methodKind: "unary";
    input: typeof AuthenticateEmailRequestSchema;
    output: typeof SessionSchema;
  },
  /**
   * @generated from rpc appsets.api.v1.AccountService.RefreshToken
   */
  refreshToken: {
    methodKind: "unary";
    input: typeof RefreshTokenRequestSchema;
    output: typeof SessionSchema;
  },
}>;

