// @generated by protoc-gen-es v2.10.0
// @generated from file api/v1/account.proto (package appsets.api.v1, syntax proto3)
/* eslint-disable */

// buf:lint:ignore PACKAGE_DIRECTORY_MATCH

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../google/api/annotations_pb";
import { file_google_protobuf_wrappers } from "@bufbuild/protobuf/wkt";
import { file_google_rpc_status } from "../../google/rpc/status_pb";

/**
 * Describes the file api/v1/account.proto.
 */
export const file_api_v1_account = /*@__PURE__*/
  fileDesc("ChRhcGkvdjEvYWNjb3VudC5wcm90bxIOYXBwc2V0cy5hcGkudjEikgEKDEFjY291bnRFbWFpbBINCgVlbWFpbBgBIAEoCRIQCghwYXNzd29yZBgCIAEoCRI0CgR2YXJzGAMgAygLMiYuYXBwc2V0cy5hcGkudjEuQWNjb3VudEVtYWlsLlZhcnNFbnRyeRorCglWYXJzRW50cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgJOgI4ASKHAQoYQXV0aGVudGljYXRlRW1haWxSZXF1ZXN0Ei0KB2FjY291bnQYASABKAsyHC5hcHBzZXRzLmFwaS52MS5BY2NvdW50RW1haWwSKgoGY3JlYXRlGAIgASgLMhouZ29vZ2xlLnByb3RvYnVmLkJvb2xWYWx1ZRIQCgh1c2VybmFtZRgDIAEoCSKYAQoPU2Vzc2lvblJlc3BvbnNlEiEKBWVycm9yGAEgASgLMhIuZ29vZ2xlLnJwYy5TdGF0dXMSDwoHY3JlYXRlZBgCIAEoCBINCgV0b2tlbhgDIAEoCRIVCg1yZWZyZXNoX3Rva2VuGAQgASgJEisKCXVzZXJfaW5mbxgFIAEoCzIYLmFwcHNldHMuYXBpLnYxLlVzZXJJbmZvInAKCFVzZXJJbmZvEgoKAmlkGAEgASgDEhAKCHVzZXJuYW1lGAIgASgJEhQKDGRpc3BsYXlfbmFtZRgDIAEoCRISCgphdmF0YXJfdXJsGAQgASgJEg0KBWVtYWlsGAUgASgJEg0KBXBob25lGAYgASgJIiQKE1JlZnJlc2hUb2tlblJlcXVlc3QSDQoFdG9rZW4YASABKAkyngIKDkFjY291bnRTZXJ2aWNlEoUBChFBdXRoZW50aWNhdGVFbWFpbBIoLmFwcHNldHMuYXBpLnYxLkF1dGhlbnRpY2F0ZUVtYWlsUmVxdWVzdBofLmFwcHNldHMuYXBpLnYxLlNlc3Npb25SZXNwb25zZSIlgtPkkwIfOgEqIhovYXBpL3YxL2F1dGhlbnRpY2F0ZS9lbWFpbBKDAQoMUmVmcmVzaFRva2VuEiMuYXBwc2V0cy5hcGkudjEuUmVmcmVzaFRva2VuUmVxdWVzdBofLmFwcHNldHMuYXBpLnYxLlNlc3Npb25SZXNwb25zZSItgtPkkwInOgEqIiIvYXBpL3YxL2F1dGhlbnRpY2F0ZS90b2tlbi9yZWZyZXNoQi1aK2dpdGh1Yi5jb20vYXBwc2V0cy9wcm90b2NvbC9nby9hcGkvdjE7YXBpcGJiBnByb3RvMw", [file_google_api_annotations, file_google_protobuf_wrappers, file_google_rpc_status]);

/**
 * Describes the message appsets.api.v1.AccountEmail.
 * Use `create(AccountEmailSchema)` to create a new message.
 */
export const AccountEmailSchema = /*@__PURE__*/
  messageDesc(file_api_v1_account, 0);

/**
 * Describes the message appsets.api.v1.AuthenticateEmailRequest.
 * Use `create(AuthenticateEmailRequestSchema)` to create a new message.
 */
export const AuthenticateEmailRequestSchema = /*@__PURE__*/
  messageDesc(file_api_v1_account, 1);

/**
 * Describes the message appsets.api.v1.SessionResponse.
 * Use `create(SessionResponseSchema)` to create a new message.
 */
export const SessionResponseSchema = /*@__PURE__*/
  messageDesc(file_api_v1_account, 2);

/**
 * Describes the message appsets.api.v1.UserInfo.
 * Use `create(UserInfoSchema)` to create a new message.
 */
export const UserInfoSchema = /*@__PURE__*/
  messageDesc(file_api_v1_account, 3);

/**
 * Describes the message appsets.api.v1.RefreshTokenRequest.
 * Use `create(RefreshTokenRequestSchema)` to create a new message.
 */
export const RefreshTokenRequestSchema = /*@__PURE__*/
  messageDesc(file_api_v1_account, 4);

/**
 * @generated from service appsets.api.v1.AccountService
 */
export const AccountService = /*@__PURE__*/
  serviceDesc(file_api_v1_account, 0);

