// @generated by protoc-gen-es v2.10.0
// @generated from file api/v1/account.proto (package appsets.api.v1, syntax proto3)
/* eslint-disable */

// buf:lint:ignore PACKAGE_DIRECTORY_MATCH

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../google/api/annotations_pb";
import { file_google_protobuf_wrappers } from "@bufbuild/protobuf/wkt";
import { file_google_rpc_status } from "../../google/rpc/status_pb";

/**
 * Describes the file api/v1/account.proto.
 */
export const file_api_v1_account = /*@__PURE__*/
  fileDesc("ChRhcGkvdjEvYWNjb3VudC5wcm90bxIOYXBwc2V0cy5hcGkudjEikgEKDEFjY291bnRFbWFpbBINCgVlbWFpbBgBIAEoCRIQCghwYXNzd29yZBgCIAEoCRI0CgR2YXJzGAMgAygLMiYuYXBwc2V0cy5hcGkudjEuQWNjb3VudEVtYWlsLlZhcnNFbnRyeRorCglWYXJzRW50cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgJOgI4ASKHAQoYQXV0aGVudGljYXRlRW1haWxSZXF1ZXN0Ei0KB2FjY291bnQYASABKAsyHC5hcHBzZXRzLmFwaS52MS5BY2NvdW50RW1haWwSKgoGY3JlYXRlGAIgASgLMhouZ29vZ2xlLnByb3RvYnVmLkJvb2xWYWx1ZRIQCgh1c2VybmFtZRgDIAEoCSKWAQoNVG9rZW5SZXNwb25zZRIhCgVlcnJvchgBIAEoCzISLmdvb2dsZS5ycGMuU3RhdHVzEg8KB2NyZWF0ZWQYAiABKAgSDQoFdG9rZW4YAyABKAkSFQoNcmVmcmVzaF90b2tlbhgEIAEoCRIrCgl1c2VyX2luZm8YBSABKAsyGC5hcHBzZXRzLmFwaS52MS5Vc2VySW5mbyJwCghVc2VySW5mbxIKCgJpZBgBIAEoAxIQCgh1c2VybmFtZRgCIAEoCRIUCgxkaXNwbGF5X25hbWUYAyABKAkSEgoKYXZhdGFyX3VybBgEIAEoCRINCgVlbWFpbBgFIAEoCRINCgVwaG9uZRgGIAEoCSIkChNSZWZyZXNoVG9rZW5SZXF1ZXN0Eg0KBXRva2VuGAEgASgJMpoCCg5BY2NvdW50U2VydmljZRKDAQoRQXV0aGVudGljYXRlRW1haWwSKC5hcHBzZXRzLmFwaS52MS5BdXRoZW50aWNhdGVFbWFpbFJlcXVlc3QaHS5hcHBzZXRzLmFwaS52MS5Ub2tlblJlc3BvbnNlIiWC0+STAh86ASoiGi9hcGkvdjEvYXV0aGVudGljYXRlL2VtYWlsEoEBCgxSZWZyZXNoVG9rZW4SIy5hcHBzZXRzLmFwaS52MS5SZWZyZXNoVG9rZW5SZXF1ZXN0Gh0uYXBwc2V0cy5hcGkudjEuVG9rZW5SZXNwb25zZSItgtPkkwInOgEqIiIvYXBpL3YxL2F1dGhlbnRpY2F0ZS90b2tlbi9yZWZyZXNoQi1aK2dpdGh1Yi5jb20vYXBwc2V0cy9wcm90b2NvbC9nby9hcGkvdjE7YXBpcGJiBnByb3RvMw", [file_google_api_annotations, file_google_protobuf_wrappers, file_google_rpc_status]);

/**
 * Describes the message appsets.api.v1.AccountEmail.
 * Use `create(AccountEmailSchema)` to create a new message.
 */
export const AccountEmailSchema = /*@__PURE__*/
  messageDesc(file_api_v1_account, 0);

/**
 * Describes the message appsets.api.v1.AuthenticateEmailRequest.
 * Use `create(AuthenticateEmailRequestSchema)` to create a new message.
 */
export const AuthenticateEmailRequestSchema = /*@__PURE__*/
  messageDesc(file_api_v1_account, 1);

/**
 * Describes the message appsets.api.v1.TokenResponse.
 * Use `create(TokenResponseSchema)` to create a new message.
 */
export const TokenResponseSchema = /*@__PURE__*/
  messageDesc(file_api_v1_account, 2);

/**
 * Describes the message appsets.api.v1.UserInfo.
 * Use `create(UserInfoSchema)` to create a new message.
 */
export const UserInfoSchema = /*@__PURE__*/
  messageDesc(file_api_v1_account, 3);

/**
 * Describes the message appsets.api.v1.RefreshTokenRequest.
 * Use `create(RefreshTokenRequestSchema)` to create a new message.
 */
export const RefreshTokenRequestSchema = /*@__PURE__*/
  messageDesc(file_api_v1_account, 4);

/**
 * @generated from service appsets.api.v1.AccountService
 */
export const AccountService = /*@__PURE__*/
  serviceDesc(file_api_v1_account, 0);

