// @generated by protoc-gen-es v2.10.0
// @generated from file api/v1/echo.proto (package appsets.api.v1, syntax proto3)
/* eslint-disable */

// buf:lint:ignore PACKAGE_DIRECTORY_MATCH

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../google/api/annotations_pb";

/**
 * Describes the file api/v1/echo.proto.
 */
export const file_api_v1_echo = /*@__PURE__*/
  fileDesc("ChFhcGkvdjEvZWNoby5wcm90bxIOYXBwc2V0cy5hcGkudjEiHAoLRWNob1JlcXVlc3QSDQoFdmFsdWUYASABKAkiHQoMRWNob1Jlc3BvbnNlEg0KBXZhbHVlGAEgASgJMmkKC0VjaG9TZXJ2aWNlEloKBEVjaG8SGy5hcHBzZXRzLmFwaS52MS5FY2hvUmVxdWVzdBocLmFwcHNldHMuYXBpLnYxLkVjaG9SZXNwb25zZSIXgtPkkwIROgEqIgwvYXBpL3YxL2VjaG9CLVorZ2l0aHViLmNvbS9hcHBzZXRzL3Byb3RvY29sL2dvL2FwaS92MTthcGlwYmIGcHJvdG8z", [file_google_api_annotations]);

/**
 * Describes the message appsets.api.v1.EchoRequest.
 * Use `create(EchoRequestSchema)` to create a new message.
 */
export const EchoRequestSchema = /*@__PURE__*/
  messageDesc(file_api_v1_echo, 0);

/**
 * Describes the message appsets.api.v1.EchoResponse.
 * Use `create(EchoResponseSchema)` to create a new message.
 */
export const EchoResponseSchema = /*@__PURE__*/
  messageDesc(file_api_v1_echo, 1);

/**
 * @generated from service appsets.api.v1.EchoService
 */
export const EchoService = /*@__PURE__*/
  serviceDesc(file_api_v1_echo, 0);

