// @generated by protoc-gen-es v2.10.0
// @generated from file api/v1/purchase.proto (package appsets.api.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../google/api/annotations_pb";

/**
 * Describes the file api/v1/purchase.proto.
 */
export const file_api_v1_purchase = /*@__PURE__*/
  fileDesc("ChVhcGkvdjEvcHVyY2hhc2UucHJvdG8SDmFwcHNldHMuYXBpLnYxIsUCCh9Jbml0aWFsaXplUHVyY2hhc2VBbGlwYXlSZXF1ZXN0EhQKDHByb2R1Y3RfdHlwZRgBIAEoCRISCgpwcm9kdWN0X2lkGAIgASgJEg0KBWNvdW50GAMgASgDEg0KBXByaWNlGAQgASgDEhQKDGFjdHVhbF9wcmljZRgFIAEoAxIUCgx0b3RhbF9hbW91bnQYBiABKAMSGwoTYWN0dWFsX3RvdGFsX2Ftb3VudBgHIAEoAxIPCgdjb21tZW50GAggASgJEk8KCG1ldGFkYXRhGAkgAygLMj0uYXBwc2V0cy5hcGkudjEuSW5pdGlhbGl6ZVB1cmNoYXNlQWxpcGF5UmVxdWVzdC5NZXRhZGF0YUVudHJ5Gi8KDU1ldGFkYXRhRW50cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgJOgI4ASJfCiBJbml0aWFsaXplUHVyY2hhc2VBbGlwYXlSZXNwb25zZRIWCg50cmFuc2FjdGlvbl9pZBgBIAEoCRIPCgdwYXlsb2FkGAIgASgJEhIKCmV4cGlyZWRfYXQYAyABKAMiHwodVmFsaWRhdGVQdXJjaGFzZUFsaXBheVJlcXVlc3QiIAoeVmFsaWRhdGVQdXJjaGFzZUFsaXBheVJlc3BvbnNlIi8KFUNhbmNlbFB1cmNoYXNlUmVxdWVzdBIWCg50cmFuc2FjdGlvbl9pZBgBIAEoCSIYChZDYW5jZWxQdXJjaGFzZVJlc3BvbnNlMu0DCg9QdXJjaGFzZVNlcnZpY2USrAEKGEluaXRpYWxpemVQdXJjaGFzZUFsaXBheRIvLmFwcHNldHMuYXBpLnYxLkluaXRpYWxpemVQdXJjaGFzZUFsaXBheVJlcXVlc3QaMC5hcHBzZXRzLmFwaS52MS5Jbml0aWFsaXplUHVyY2hhc2VBbGlwYXlSZXNwb25zZSItgtPkkwInOgEqIiIvYXBpL3YxL3B1cmNoYXNlL2FsaXBheS9pbml0aWFsaXplEqQBChZWYWxpZGF0ZVB1cmNoYXNlQWxpcGF5Ei0uYXBwc2V0cy5hcGkudjEuVmFsaWRhdGVQdXJjaGFzZUFsaXBheVJlcXVlc3QaLi5hcHBzZXRzLmFwaS52MS5WYWxpZGF0ZVB1cmNoYXNlQWxpcGF5UmVzcG9uc2UiK4LT5JMCJToBKiIgL2FwaS92MS9wdXJjaGFzZS9hbGlwYXkvdmFsaWRhdGUSgwEKDkNhbmNlbFB1cmNoYXNlEiUuYXBwc2V0cy5hcGkudjEuQ2FuY2VsUHVyY2hhc2VSZXF1ZXN0GiYuYXBwc2V0cy5hcGkudjEuQ2FuY2VsUHVyY2hhc2VSZXNwb25zZSIigtPkkwIcOgEqIhcvYXBpL3YxL3B1cmNoYXNlL2NhbmNlbEItWitnaXRodWIuY29tL2FwcHNldHMvcHJvdG9jb2wvZ28vYXBpL3YxO2FwaXBiYgZwcm90bzM", [file_google_api_annotations]);

/**
 * Describes the message appsets.api.v1.InitializePurchaseAlipayRequest.
 * Use `create(InitializePurchaseAlipayRequestSchema)` to create a new message.
 */
export const InitializePurchaseAlipayRequestSchema = /*@__PURE__*/
  messageDesc(file_api_v1_purchase, 0);

/**
 * Describes the message appsets.api.v1.InitializePurchaseAlipayResponse.
 * Use `create(InitializePurchaseAlipayResponseSchema)` to create a new message.
 */
export const InitializePurchaseAlipayResponseSchema = /*@__PURE__*/
  messageDesc(file_api_v1_purchase, 1);

/**
 * Describes the message appsets.api.v1.ValidatePurchaseAlipayRequest.
 * Use `create(ValidatePurchaseAlipayRequestSchema)` to create a new message.
 */
export const ValidatePurchaseAlipayRequestSchema = /*@__PURE__*/
  messageDesc(file_api_v1_purchase, 2);

/**
 * Describes the message appsets.api.v1.ValidatePurchaseAlipayResponse.
 * Use `create(ValidatePurchaseAlipayResponseSchema)` to create a new message.
 */
export const ValidatePurchaseAlipayResponseSchema = /*@__PURE__*/
  messageDesc(file_api_v1_purchase, 3);

/**
 * Describes the message appsets.api.v1.CancelPurchaseRequest.
 * Use `create(CancelPurchaseRequestSchema)` to create a new message.
 */
export const CancelPurchaseRequestSchema = /*@__PURE__*/
  messageDesc(file_api_v1_purchase, 4);

/**
 * Describes the message appsets.api.v1.CancelPurchaseResponse.
 * Use `create(CancelPurchaseResponseSchema)` to create a new message.
 */
export const CancelPurchaseResponseSchema = /*@__PURE__*/
  messageDesc(file_api_v1_purchase, 5);

/**
 * @generated from service appsets.api.v1.PurchaseService
 */
export const PurchaseService = /*@__PURE__*/
  serviceDesc(file_api_v1_purchase, 0);

