// @generated by protoc-gen-es v2.10.0
// @generated from file api/v1/purchase.proto (package appsets.api.v1, syntax proto3)
/* eslint-disable */

// buf:lint:ignore PACKAGE_DIRECTORY_MATCH

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Status } from "../../google/rpc/status_pb";

/**
 * Describes the file api/v1/purchase.proto.
 */
export declare const file_api_v1_purchase: GenFile;

/**
 * @generated from message appsets.api.v1.InitializePurchaseAlipayRequest
 */
export declare type InitializePurchaseAlipayRequest = Message<"appsets.api.v1.InitializePurchaseAlipayRequest"> & {
  /**
   * @generated from field: string product_type = 1;
   */
  productType: string;

  /**
   * @generated from field: string product_id = 2;
   */
  productId: string;

  /**
   * @generated from field: int64 count = 3;
   */
  count: bigint;

  /**
   * @generated from field: int64 price = 4;
   */
  price: bigint;

  /**
   * @generated from field: int64 actual_price = 5;
   */
  actualPrice: bigint;

  /**
   * @generated from field: int64 total_amount = 6;
   */
  totalAmount: bigint;

  /**
   * @generated from field: int64 actual_total_amount = 7;
   */
  actualTotalAmount: bigint;

  /**
   * @generated from field: string comment = 8;
   */
  comment: string;

  /**
   * @generated from field: map<string, string> metadata = 9;
   */
  metadata: { [key: string]: string };
};

/**
 * Describes the message appsets.api.v1.InitializePurchaseAlipayRequest.
 * Use `create(InitializePurchaseAlipayRequestSchema)` to create a new message.
 */
export declare const InitializePurchaseAlipayRequestSchema: GenMessage<InitializePurchaseAlipayRequest>;

/**
 * @generated from message appsets.api.v1.InitializePurchaseAlipayResponse
 */
export declare type InitializePurchaseAlipayResponse = Message<"appsets.api.v1.InitializePurchaseAlipayResponse"> & {
  /**
   * @generated from field: google.rpc.Status error = 1;
   */
  error?: Status;

  /**
   * @generated from field: string transaction_id = 2;
   */
  transactionId: string;

  /**
   * @generated from field: string payload = 3;
   */
  payload: string;

  /**
   * @generated from field: int64 expired_at = 4;
   */
  expiredAt: bigint;
};

/**
 * Describes the message appsets.api.v1.InitializePurchaseAlipayResponse.
 * Use `create(InitializePurchaseAlipayResponseSchema)` to create a new message.
 */
export declare const InitializePurchaseAlipayResponseSchema: GenMessage<InitializePurchaseAlipayResponse>;

/**
 * @generated from message appsets.api.v1.ValidatePurchaseAlipayRequest
 */
export declare type ValidatePurchaseAlipayRequest = Message<"appsets.api.v1.ValidatePurchaseAlipayRequest"> & {
};

/**
 * Describes the message appsets.api.v1.ValidatePurchaseAlipayRequest.
 * Use `create(ValidatePurchaseAlipayRequestSchema)` to create a new message.
 */
export declare const ValidatePurchaseAlipayRequestSchema: GenMessage<ValidatePurchaseAlipayRequest>;

/**
 * @generated from message appsets.api.v1.ValidatePurchaseAlipayResponse
 */
export declare type ValidatePurchaseAlipayResponse = Message<"appsets.api.v1.ValidatePurchaseAlipayResponse"> & {
  /**
   * @generated from field: google.rpc.Status error = 1;
   */
  error?: Status;
};

/**
 * Describes the message appsets.api.v1.ValidatePurchaseAlipayResponse.
 * Use `create(ValidatePurchaseAlipayResponseSchema)` to create a new message.
 */
export declare const ValidatePurchaseAlipayResponseSchema: GenMessage<ValidatePurchaseAlipayResponse>;

/**
 * @generated from message appsets.api.v1.CancelPurchaseRequest
 */
export declare type CancelPurchaseRequest = Message<"appsets.api.v1.CancelPurchaseRequest"> & {
  /**
   * @generated from field: string transaction_id = 1;
   */
  transactionId: string;
};

/**
 * Describes the message appsets.api.v1.CancelPurchaseRequest.
 * Use `create(CancelPurchaseRequestSchema)` to create a new message.
 */
export declare const CancelPurchaseRequestSchema: GenMessage<CancelPurchaseRequest>;

/**
 * @generated from message appsets.api.v1.CancelPurchaseResponse
 */
export declare type CancelPurchaseResponse = Message<"appsets.api.v1.CancelPurchaseResponse"> & {
  /**
   * @generated from field: google.rpc.Status error = 1;
   */
  error?: Status;
};

/**
 * Describes the message appsets.api.v1.CancelPurchaseResponse.
 * Use `create(CancelPurchaseResponseSchema)` to create a new message.
 */
export declare const CancelPurchaseResponseSchema: GenMessage<CancelPurchaseResponse>;

/**
 * @generated from service appsets.api.v1.PurchaseService
 */
export declare const PurchaseService: GenService<{
  /**
   * @generated from rpc appsets.api.v1.PurchaseService.InitializePurchaseAlipay
   */
  initializePurchaseAlipay: {
    methodKind: "unary";
    input: typeof InitializePurchaseAlipayRequestSchema;
    output: typeof InitializePurchaseAlipayResponseSchema;
  },
  /**
   * @generated from rpc appsets.api.v1.PurchaseService.ValidatePurchaseAlipay
   */
  validatePurchaseAlipay: {
    methodKind: "unary";
    input: typeof ValidatePurchaseAlipayRequestSchema;
    output: typeof ValidatePurchaseAlipayResponseSchema;
  },
  /**
   * @generated from rpc appsets.api.v1.PurchaseService.CancelPurchase
   */
  cancelPurchase: {
    methodKind: "unary";
    input: typeof CancelPurchaseRequestSchema;
    output: typeof CancelPurchaseResponseSchema;
  },
}>;

