// @generated by protoc-gen-es v2.10.0
// @generated from file api/v1/purchase.proto (package appsets.api.v1, syntax proto3)
/* eslint-disable */

// buf:lint:ignore PACKAGE_DIRECTORY_MATCH

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../google/api/annotations_pb";
import { file_google_rpc_status } from "../../google/rpc/status_pb";

/**
 * Describes the file api/v1/purchase.proto.
 */
export const file_api_v1_purchase = /*@__PURE__*/
  fileDesc("ChVhcGkvdjEvcHVyY2hhc2UucHJvdG8SDmFwcHNldHMuYXBpLnYxIsUCCh9Jbml0aWFsaXplUHVyY2hhc2VBbGlwYXlSZXF1ZXN0EhQKDHByb2R1Y3RfdHlwZRgBIAEoCRISCgpwcm9kdWN0X2lkGAIgASgJEg0KBWNvdW50GAMgASgDEg0KBXByaWNlGAQgASgDEhQKDGFjdHVhbF9wcmljZRgFIAEoAxIUCgx0b3RhbF9hbW91bnQYBiABKAMSGwoTYWN0dWFsX3RvdGFsX2Ftb3VudBgHIAEoAxIPCgdjb21tZW50GAggASgJEk8KCG1ldGFkYXRhGAkgAygLMj0uYXBwc2V0cy5hcGkudjEuSW5pdGlhbGl6ZVB1cmNoYXNlQWxpcGF5UmVxdWVzdC5NZXRhZGF0YUVudHJ5Gi8KDU1ldGFkYXRhRW50cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgJOgI4ASKCAQogSW5pdGlhbGl6ZVB1cmNoYXNlQWxpcGF5UmVzcG9uc2USIQoFZXJyb3IYASABKAsyEi5nb29nbGUucnBjLlN0YXR1cxIWCg50cmFuc2FjdGlvbl9pZBgCIAEoCRIPCgdwYXlsb2FkGAMgASgJEhIKCmV4cGlyZWRfYXQYBCABKAMiHwodVmFsaWRhdGVQdXJjaGFzZUFsaXBheVJlcXVlc3QiQwoeVmFsaWRhdGVQdXJjaGFzZUFsaXBheVJlc3BvbnNlEiEKBWVycm9yGAEgASgLMhIuZ29vZ2xlLnJwYy5TdGF0dXMiLwoVQ2FuY2VsUHVyY2hhc2VSZXF1ZXN0EhYKDnRyYW5zYWN0aW9uX2lkGAEgASgJIjsKFkNhbmNlbFB1cmNoYXNlUmVzcG9uc2USIQoFZXJyb3IYASABKAsyEi5nb29nbGUucnBjLlN0YXR1czLtAwoPUHVyY2hhc2VTZXJ2aWNlEqwBChhJbml0aWFsaXplUHVyY2hhc2VBbGlwYXkSLy5hcHBzZXRzLmFwaS52MS5Jbml0aWFsaXplUHVyY2hhc2VBbGlwYXlSZXF1ZXN0GjAuYXBwc2V0cy5hcGkudjEuSW5pdGlhbGl6ZVB1cmNoYXNlQWxpcGF5UmVzcG9uc2UiLYLT5JMCJzoBKiIiL2FwaS92MS9wdXJjaGFzZS9hbGlwYXkvaW5pdGlhbGl6ZRKkAQoWVmFsaWRhdGVQdXJjaGFzZUFsaXBheRItLmFwcHNldHMuYXBpLnYxLlZhbGlkYXRlUHVyY2hhc2VBbGlwYXlSZXF1ZXN0Gi4uYXBwc2V0cy5hcGkudjEuVmFsaWRhdGVQdXJjaGFzZUFsaXBheVJlc3BvbnNlIiuC0+STAiU6ASoiIC9hcGkvdjEvcHVyY2hhc2UvYWxpcGF5L3ZhbGlkYXRlEoMBCg5DYW5jZWxQdXJjaGFzZRIlLmFwcHNldHMuYXBpLnYxLkNhbmNlbFB1cmNoYXNlUmVxdWVzdBomLmFwcHNldHMuYXBpLnYxLkNhbmNlbFB1cmNoYXNlUmVzcG9uc2UiIoLT5JMCHDoBKiIXL2FwaS92MS9wdXJjaGFzZS9jYW5jZWxCLVorZ2l0aHViLmNvbS9hcHBzZXRzL3Byb3RvY29sL2dvL2FwaS92MTthcGlwYmIGcHJvdG8z", [file_google_api_annotations, file_google_rpc_status]);

/**
 * Describes the message appsets.api.v1.InitializePurchaseAlipayRequest.
 * Use `create(InitializePurchaseAlipayRequestSchema)` to create a new message.
 */
export const InitializePurchaseAlipayRequestSchema = /*@__PURE__*/
  messageDesc(file_api_v1_purchase, 0);

/**
 * Describes the message appsets.api.v1.InitializePurchaseAlipayResponse.
 * Use `create(InitializePurchaseAlipayResponseSchema)` to create a new message.
 */
export const InitializePurchaseAlipayResponseSchema = /*@__PURE__*/
  messageDesc(file_api_v1_purchase, 1);

/**
 * Describes the message appsets.api.v1.ValidatePurchaseAlipayRequest.
 * Use `create(ValidatePurchaseAlipayRequestSchema)` to create a new message.
 */
export const ValidatePurchaseAlipayRequestSchema = /*@__PURE__*/
  messageDesc(file_api_v1_purchase, 2);

/**
 * Describes the message appsets.api.v1.ValidatePurchaseAlipayResponse.
 * Use `create(ValidatePurchaseAlipayResponseSchema)` to create a new message.
 */
export const ValidatePurchaseAlipayResponseSchema = /*@__PURE__*/
  messageDesc(file_api_v1_purchase, 3);

/**
 * Describes the message appsets.api.v1.CancelPurchaseRequest.
 * Use `create(CancelPurchaseRequestSchema)` to create a new message.
 */
export const CancelPurchaseRequestSchema = /*@__PURE__*/
  messageDesc(file_api_v1_purchase, 4);

/**
 * Describes the message appsets.api.v1.CancelPurchaseResponse.
 * Use `create(CancelPurchaseResponseSchema)` to create a new message.
 */
export const CancelPurchaseResponseSchema = /*@__PURE__*/
  messageDesc(file_api_v1_purchase, 5);

/**
 * @generated from service appsets.api.v1.PurchaseService
 */
export const PurchaseService = /*@__PURE__*/
  serviceDesc(file_api_v1_purchase, 0);

