// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: api/v1/purchase.proto

package apipb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PurchaseService_InitializePurchaseAlipay_FullMethodName = "/appsets.api.v1.PurchaseService/InitializePurchaseAlipay"
	PurchaseService_ValidatePurchaseAlipay_FullMethodName   = "/appsets.api.v1.PurchaseService/ValidatePurchaseAlipay"
	PurchaseService_CancelPurchase_FullMethodName           = "/appsets.api.v1.PurchaseService/CancelPurchase"
)

// PurchaseServiceClient is the client API for PurchaseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PurchaseServiceClient interface {
	InitializePurchaseAlipay(ctx context.Context, in *InitializePurchaseAlipayRequest, opts ...grpc.CallOption) (*InitializePurchaseAlipayResponse, error)
	ValidatePurchaseAlipay(ctx context.Context, in *ValidatePurchaseAlipayRequest, opts ...grpc.CallOption) (*ValidatePurchaseAlipayResponse, error)
	CancelPurchase(ctx context.Context, in *CancelPurchaseRequest, opts ...grpc.CallOption) (*CancelPurchaseResponse, error)
}

type purchaseServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPurchaseServiceClient(cc grpc.ClientConnInterface) PurchaseServiceClient {
	return &purchaseServiceClient{cc}
}

func (c *purchaseServiceClient) InitializePurchaseAlipay(ctx context.Context, in *InitializePurchaseAlipayRequest, opts ...grpc.CallOption) (*InitializePurchaseAlipayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitializePurchaseAlipayResponse)
	err := c.cc.Invoke(ctx, PurchaseService_InitializePurchaseAlipay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *purchaseServiceClient) ValidatePurchaseAlipay(ctx context.Context, in *ValidatePurchaseAlipayRequest, opts ...grpc.CallOption) (*ValidatePurchaseAlipayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidatePurchaseAlipayResponse)
	err := c.cc.Invoke(ctx, PurchaseService_ValidatePurchaseAlipay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *purchaseServiceClient) CancelPurchase(ctx context.Context, in *CancelPurchaseRequest, opts ...grpc.CallOption) (*CancelPurchaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelPurchaseResponse)
	err := c.cc.Invoke(ctx, PurchaseService_CancelPurchase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PurchaseServiceServer is the server API for PurchaseService service.
// All implementations must embed UnimplementedPurchaseServiceServer
// for forward compatibility.
type PurchaseServiceServer interface {
	InitializePurchaseAlipay(context.Context, *InitializePurchaseAlipayRequest) (*InitializePurchaseAlipayResponse, error)
	ValidatePurchaseAlipay(context.Context, *ValidatePurchaseAlipayRequest) (*ValidatePurchaseAlipayResponse, error)
	CancelPurchase(context.Context, *CancelPurchaseRequest) (*CancelPurchaseResponse, error)
	mustEmbedUnimplementedPurchaseServiceServer()
}

// UnimplementedPurchaseServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPurchaseServiceServer struct{}

func (UnimplementedPurchaseServiceServer) InitializePurchaseAlipay(context.Context, *InitializePurchaseAlipayRequest) (*InitializePurchaseAlipayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitializePurchaseAlipay not implemented")
}
func (UnimplementedPurchaseServiceServer) ValidatePurchaseAlipay(context.Context, *ValidatePurchaseAlipayRequest) (*ValidatePurchaseAlipayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidatePurchaseAlipay not implemented")
}
func (UnimplementedPurchaseServiceServer) CancelPurchase(context.Context, *CancelPurchaseRequest) (*CancelPurchaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelPurchase not implemented")
}
func (UnimplementedPurchaseServiceServer) mustEmbedUnimplementedPurchaseServiceServer() {}
func (UnimplementedPurchaseServiceServer) testEmbeddedByValue()                         {}

// UnsafePurchaseServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PurchaseServiceServer will
// result in compilation errors.
type UnsafePurchaseServiceServer interface {
	mustEmbedUnimplementedPurchaseServiceServer()
}

func RegisterPurchaseServiceServer(s grpc.ServiceRegistrar, srv PurchaseServiceServer) {
	// If the following call pancis, it indicates UnimplementedPurchaseServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PurchaseService_ServiceDesc, srv)
}

func _PurchaseService_InitializePurchaseAlipay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitializePurchaseAlipayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PurchaseServiceServer).InitializePurchaseAlipay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PurchaseService_InitializePurchaseAlipay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PurchaseServiceServer).InitializePurchaseAlipay(ctx, req.(*InitializePurchaseAlipayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PurchaseService_ValidatePurchaseAlipay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidatePurchaseAlipayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PurchaseServiceServer).ValidatePurchaseAlipay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PurchaseService_ValidatePurchaseAlipay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PurchaseServiceServer).ValidatePurchaseAlipay(ctx, req.(*ValidatePurchaseAlipayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PurchaseService_CancelPurchase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelPurchaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PurchaseServiceServer).CancelPurchase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PurchaseService_CancelPurchase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PurchaseServiceServer).CancelPurchase(ctx, req.(*CancelPurchaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PurchaseService_ServiceDesc is the grpc.ServiceDesc for PurchaseService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PurchaseService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "appsets.api.v1.PurchaseService",
	HandlerType: (*PurchaseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitializePurchaseAlipay",
			Handler:    _PurchaseService_InitializePurchaseAlipay_Handler,
		},
		{
			MethodName: "ValidatePurchaseAlipay",
			Handler:    _PurchaseService_ValidatePurchaseAlipay_Handler,
		},
		{
			MethodName: "CancelPurchase",
			Handler:    _PurchaseService_CancelPurchase_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/purchase.proto",
}
