// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: api/v1/purchase.proto

// buf:lint:ignore PACKAGE_DIRECTORY_MATCH

package apipb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	status "google.golang.org/genproto/googleapis/rpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitializePurchaseAlipayRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ProductType       string                 `protobuf:"bytes,1,opt,name=product_type,json=productType,proto3" json:"product_type,omitempty"`
	ProductId         string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Count             int64                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	Price             int64                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	ActualPrice       int64                  `protobuf:"varint,5,opt,name=actual_price,json=actualPrice,proto3" json:"actual_price,omitempty"`
	TotalAmount       int64                  `protobuf:"varint,6,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	ActualTotalAmount int64                  `protobuf:"varint,7,opt,name=actual_total_amount,json=actualTotalAmount,proto3" json:"actual_total_amount,omitempty"`
	Comment           string                 `protobuf:"bytes,8,opt,name=comment,proto3" json:"comment,omitempty"`
	Metadata          map[string]string      `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *InitializePurchaseAlipayRequest) Reset() {
	*x = InitializePurchaseAlipayRequest{}
	mi := &file_api_v1_purchase_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializePurchaseAlipayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializePurchaseAlipayRequest) ProtoMessage() {}

func (x *InitializePurchaseAlipayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_purchase_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializePurchaseAlipayRequest.ProtoReflect.Descriptor instead.
func (*InitializePurchaseAlipayRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_purchase_proto_rawDescGZIP(), []int{0}
}

func (x *InitializePurchaseAlipayRequest) GetProductType() string {
	if x != nil {
		return x.ProductType
	}
	return ""
}

func (x *InitializePurchaseAlipayRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *InitializePurchaseAlipayRequest) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *InitializePurchaseAlipayRequest) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *InitializePurchaseAlipayRequest) GetActualPrice() int64 {
	if x != nil {
		return x.ActualPrice
	}
	return 0
}

func (x *InitializePurchaseAlipayRequest) GetTotalAmount() int64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *InitializePurchaseAlipayRequest) GetActualTotalAmount() int64 {
	if x != nil {
		return x.ActualTotalAmount
	}
	return 0
}

func (x *InitializePurchaseAlipayRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *InitializePurchaseAlipayRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type InitializePurchaseAlipayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *status.Status         `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	TransactionId string                 `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Payload       string                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	ExpiredAt     int64                  `protobuf:"varint,4,opt,name=expired_at,json=expiredAt,proto3" json:"expired_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitializePurchaseAlipayResponse) Reset() {
	*x = InitializePurchaseAlipayResponse{}
	mi := &file_api_v1_purchase_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializePurchaseAlipayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializePurchaseAlipayResponse) ProtoMessage() {}

func (x *InitializePurchaseAlipayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_purchase_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializePurchaseAlipayResponse.ProtoReflect.Descriptor instead.
func (*InitializePurchaseAlipayResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_purchase_proto_rawDescGZIP(), []int{1}
}

func (x *InitializePurchaseAlipayResponse) GetError() *status.Status {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *InitializePurchaseAlipayResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *InitializePurchaseAlipayResponse) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *InitializePurchaseAlipayResponse) GetExpiredAt() int64 {
	if x != nil {
		return x.ExpiredAt
	}
	return 0
}

type ValidatePurchaseAlipayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidatePurchaseAlipayRequest) Reset() {
	*x = ValidatePurchaseAlipayRequest{}
	mi := &file_api_v1_purchase_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatePurchaseAlipayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatePurchaseAlipayRequest) ProtoMessage() {}

func (x *ValidatePurchaseAlipayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_purchase_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatePurchaseAlipayRequest.ProtoReflect.Descriptor instead.
func (*ValidatePurchaseAlipayRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_purchase_proto_rawDescGZIP(), []int{2}
}

type ValidatePurchaseAlipayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *status.Status         `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidatePurchaseAlipayResponse) Reset() {
	*x = ValidatePurchaseAlipayResponse{}
	mi := &file_api_v1_purchase_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatePurchaseAlipayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatePurchaseAlipayResponse) ProtoMessage() {}

func (x *ValidatePurchaseAlipayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_purchase_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatePurchaseAlipayResponse.ProtoReflect.Descriptor instead.
func (*ValidatePurchaseAlipayResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_purchase_proto_rawDescGZIP(), []int{3}
}

func (x *ValidatePurchaseAlipayResponse) GetError() *status.Status {
	if x != nil {
		return x.Error
	}
	return nil
}

type CancelPurchaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelPurchaseRequest) Reset() {
	*x = CancelPurchaseRequest{}
	mi := &file_api_v1_purchase_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelPurchaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelPurchaseRequest) ProtoMessage() {}

func (x *CancelPurchaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_purchase_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelPurchaseRequest.ProtoReflect.Descriptor instead.
func (*CancelPurchaseRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_purchase_proto_rawDescGZIP(), []int{4}
}

func (x *CancelPurchaseRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

type CancelPurchaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *status.Status         `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelPurchaseResponse) Reset() {
	*x = CancelPurchaseResponse{}
	mi := &file_api_v1_purchase_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelPurchaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelPurchaseResponse) ProtoMessage() {}

func (x *CancelPurchaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_purchase_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelPurchaseResponse.ProtoReflect.Descriptor instead.
func (*CancelPurchaseResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_purchase_proto_rawDescGZIP(), []int{5}
}

func (x *CancelPurchaseResponse) GetError() *status.Status {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_api_v1_purchase_proto protoreflect.FileDescriptor

const file_api_v1_purchase_proto_rawDesc = "" +
	"\n" +
	"\x15api/v1/purchase.proto\x12\x0eappsets.api.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/rpc/status.proto\"\xb7\x03\n" +
	"\x1fInitializePurchaseAlipayRequest\x12!\n" +
	"\fproduct_type\x18\x01 \x01(\tR\vproductType\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x03R\x05count\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x03R\x05price\x12!\n" +
	"\factual_price\x18\x05 \x01(\x03R\vactualPrice\x12!\n" +
	"\ftotal_amount\x18\x06 \x01(\x03R\vtotalAmount\x12.\n" +
	"\x13actual_total_amount\x18\a \x01(\x03R\x11actualTotalAmount\x12\x18\n" +
	"\acomment\x18\b \x01(\tR\acomment\x12Y\n" +
	"\bmetadata\x18\t \x03(\v2=.appsets.api.v1.InitializePurchaseAlipayRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xac\x01\n" +
	" InitializePurchaseAlipayResponse\x12(\n" +
	"\x05error\x18\x01 \x01(\v2\x12.google.rpc.StatusR\x05error\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\x12\x18\n" +
	"\apayload\x18\x03 \x01(\tR\apayload\x12\x1d\n" +
	"\n" +
	"expired_at\x18\x04 \x01(\x03R\texpiredAt\"\x1f\n" +
	"\x1dValidatePurchaseAlipayRequest\"J\n" +
	"\x1eValidatePurchaseAlipayResponse\x12(\n" +
	"\x05error\x18\x01 \x01(\v2\x12.google.rpc.StatusR\x05error\">\n" +
	"\x15CancelPurchaseRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\"B\n" +
	"\x16CancelPurchaseResponse\x12(\n" +
	"\x05error\x18\x01 \x01(\v2\x12.google.rpc.StatusR\x05error2\xed\x03\n" +
	"\x0fPurchaseService\x12\xac\x01\n" +
	"\x18InitializePurchaseAlipay\x12/.appsets.api.v1.InitializePurchaseAlipayRequest\x1a0.appsets.api.v1.InitializePurchaseAlipayResponse\"-\x82\xd3\xe4\x93\x02':\x01*\"\"/api/v1/purchase/alipay/initialize\x12\xa4\x01\n" +
	"\x16ValidatePurchaseAlipay\x12-.appsets.api.v1.ValidatePurchaseAlipayRequest\x1a..appsets.api.v1.ValidatePurchaseAlipayResponse\"+\x82\xd3\xe4\x93\x02%:\x01*\" /api/v1/purchase/alipay/validate\x12\x83\x01\n" +
	"\x0eCancelPurchase\x12%.appsets.api.v1.CancelPurchaseRequest\x1a&.appsets.api.v1.CancelPurchaseResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/api/v1/purchase/cancelB-Z+github.com/appsets/protocol/go/api/v1;apipbb\x06proto3"

var (
	file_api_v1_purchase_proto_rawDescOnce sync.Once
	file_api_v1_purchase_proto_rawDescData []byte
)

func file_api_v1_purchase_proto_rawDescGZIP() []byte {
	file_api_v1_purchase_proto_rawDescOnce.Do(func() {
		file_api_v1_purchase_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_purchase_proto_rawDesc), len(file_api_v1_purchase_proto_rawDesc)))
	})
	return file_api_v1_purchase_proto_rawDescData
}

var file_api_v1_purchase_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_v1_purchase_proto_goTypes = []any{
	(*InitializePurchaseAlipayRequest)(nil),  // 0: appsets.api.v1.InitializePurchaseAlipayRequest
	(*InitializePurchaseAlipayResponse)(nil), // 1: appsets.api.v1.InitializePurchaseAlipayResponse
	(*ValidatePurchaseAlipayRequest)(nil),    // 2: appsets.api.v1.ValidatePurchaseAlipayRequest
	(*ValidatePurchaseAlipayResponse)(nil),   // 3: appsets.api.v1.ValidatePurchaseAlipayResponse
	(*CancelPurchaseRequest)(nil),            // 4: appsets.api.v1.CancelPurchaseRequest
	(*CancelPurchaseResponse)(nil),           // 5: appsets.api.v1.CancelPurchaseResponse
	nil,                                      // 6: appsets.api.v1.InitializePurchaseAlipayRequest.MetadataEntry
	(*status.Status)(nil),                    // 7: google.rpc.Status
}
var file_api_v1_purchase_proto_depIdxs = []int32{
	6, // 0: appsets.api.v1.InitializePurchaseAlipayRequest.metadata:type_name -> appsets.api.v1.InitializePurchaseAlipayRequest.MetadataEntry
	7, // 1: appsets.api.v1.InitializePurchaseAlipayResponse.error:type_name -> google.rpc.Status
	7, // 2: appsets.api.v1.ValidatePurchaseAlipayResponse.error:type_name -> google.rpc.Status
	7, // 3: appsets.api.v1.CancelPurchaseResponse.error:type_name -> google.rpc.Status
	0, // 4: appsets.api.v1.PurchaseService.InitializePurchaseAlipay:input_type -> appsets.api.v1.InitializePurchaseAlipayRequest
	2, // 5: appsets.api.v1.PurchaseService.ValidatePurchaseAlipay:input_type -> appsets.api.v1.ValidatePurchaseAlipayRequest
	4, // 6: appsets.api.v1.PurchaseService.CancelPurchase:input_type -> appsets.api.v1.CancelPurchaseRequest
	1, // 7: appsets.api.v1.PurchaseService.InitializePurchaseAlipay:output_type -> appsets.api.v1.InitializePurchaseAlipayResponse
	3, // 8: appsets.api.v1.PurchaseService.ValidatePurchaseAlipay:output_type -> appsets.api.v1.ValidatePurchaseAlipayResponse
	5, // 9: appsets.api.v1.PurchaseService.CancelPurchase:output_type -> appsets.api.v1.CancelPurchaseResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_v1_purchase_proto_init() }
func file_api_v1_purchase_proto_init() {
	if File_api_v1_purchase_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_purchase_proto_rawDesc), len(file_api_v1_purchase_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_purchase_proto_goTypes,
		DependencyIndexes: file_api_v1_purchase_proto_depIdxs,
		MessageInfos:      file_api_v1_purchase_proto_msgTypes,
	}.Build()
	File_api_v1_purchase_proto = out.File
	file_api_v1_purchase_proto_goTypes = nil
	file_api_v1_purchase_proto_depIdxs = nil
}
