// @generated by protoc-gen-es v2.10.0
// @generated from file openapi/v1/echo.proto (package appsets.openapi.v1, syntax proto3)
/* eslint-disable */

// buf:lint:ignore PACKAGE_DIRECTORY_MATCH

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../google/api/annotations_pb";

/**
 * Describes the file openapi/v1/echo.proto.
 */
export const file_openapi_v1_echo = /*@__PURE__*/
  fileDesc("ChVvcGVuYXBpL3YxL2VjaG8ucHJvdG8SEmFwcHNldHMub3BlbmFwaS52MSIcCgtFY2hvUmVxdWVzdBINCgV2YWx1ZRgBIAEoCSIdCgxFY2hvUmVzcG9uc2USDQoFdmFsdWUYASABKAkycQoLRWNob1NlcnZpY2USYgoERWNobxIfLmFwcHNldHMub3BlbmFwaS52MS5FY2hvUmVxdWVzdBogLmFwcHNldHMub3BlbmFwaS52MS5FY2hvUmVzcG9uc2UiF4LT5JMCEToBKiIML2FwaS92MS9lY2hvQjVaM2dpdGh1Yi5jb20vYXBwc2V0cy9wcm90b2NvbC9nby9vcGVuYXBpL3YxO29wZW5hcGlwYmIGcHJvdG8z", [file_google_api_annotations]);

/**
 * Describes the message appsets.openapi.v1.EchoRequest.
 * Use `create(EchoRequestSchema)` to create a new message.
 */
export const EchoRequestSchema = /*@__PURE__*/
  messageDesc(file_openapi_v1_echo, 0);

/**
 * Describes the message appsets.openapi.v1.EchoResponse.
 * Use `create(EchoResponseSchema)` to create a new message.
 */
export const EchoResponseSchema = /*@__PURE__*/
  messageDesc(file_openapi_v1_echo, 1);

/**
 * @generated from service appsets.openapi.v1.EchoService
 */
export const EchoService = /*@__PURE__*/
  serviceDesc(file_openapi_v1_echo, 0);

