// @generated by protoc-gen-es v2.10.0
// @generated from file openapi/v1/echo.proto (package appsets.openapi.v1, syntax proto3)
/* eslint-disable */

// buf:lint:ignore PACKAGE_DIRECTORY_MATCH

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file openapi/v1/echo.proto.
 */
export declare const file_openapi_v1_echo: GenFile;

/**
 * @generated from message appsets.openapi.v1.EchoRequest
 */
export declare type EchoRequest = Message<"appsets.openapi.v1.EchoRequest"> & {
  /**
   * @generated from field: string value = 1;
   */
  value: string;
};

/**
 * Describes the message appsets.openapi.v1.EchoRequest.
 * Use `create(EchoRequestSchema)` to create a new message.
 */
export declare const EchoRequestSchema: GenMessage<EchoRequest>;

/**
 * @generated from message appsets.openapi.v1.EchoResponse
 */
export declare type EchoResponse = Message<"appsets.openapi.v1.EchoResponse"> & {
  /**
   * @generated from field: string value = 1;
   */
  value: string;
};

/**
 * Describes the message appsets.openapi.v1.EchoResponse.
 * Use `create(EchoResponseSchema)` to create a new message.
 */
export declare const EchoResponseSchema: GenMessage<EchoResponse>;

/**
 * @generated from service appsets.openapi.v1.EchoService
 */
export declare const EchoService: GenService<{
  /**
   * @generated from rpc appsets.openapi.v1.EchoService.Echo
   */
  echo: {
    methodKind: "unary";
    input: typeof EchoRequestSchema;
    output: typeof EchoResponseSchema;
  },
}>;

