// @generated by protoc-gen-es v2.10.0
// @generated from file openapi/v1/organization.proto (package appsets.openapi.v1, syntax proto3)
/* eslint-disable */

// buf:lint:ignore PACKAGE_DIRECTORY_MATCH

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Status } from "../../google/rpc/status_pb";

/**
 * Describes the file openapi/v1/organization.proto.
 */
export declare const file_openapi_v1_organization: GenFile;

/**
 * @generated from message appsets.openapi.v1.CreateOrganizationRequest
 */
export declare type CreateOrganizationRequest = Message<"appsets.openapi.v1.CreateOrganizationRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string code = 2;
   */
  code: string;

  /**
   * @generated from field: string name = 3;
   */
  name: string;

  /**
   * @generated from field: string owned_by = 4;
   */
  ownedBy: string;

  /**
   * @generated from field: string created_by = 5;
   */
  createdBy: string;
};

/**
 * Describes the message appsets.openapi.v1.CreateOrganizationRequest.
 * Use `create(CreateOrganizationRequestSchema)` to create a new message.
 */
export declare const CreateOrganizationRequestSchema: GenMessage<CreateOrganizationRequest>;

/**
 * @generated from message appsets.openapi.v1.CreateOrganizationResponse
 */
export declare type CreateOrganizationResponse = Message<"appsets.openapi.v1.CreateOrganizationResponse"> & {
  /**
   * @generated from field: google.rpc.Status error = 1;
   */
  error?: Status;
};

/**
 * Describes the message appsets.openapi.v1.CreateOrganizationResponse.
 * Use `create(CreateOrganizationResponseSchema)` to create a new message.
 */
export declare const CreateOrganizationResponseSchema: GenMessage<CreateOrganizationResponse>;

/**
 * @generated from service appsets.openapi.v1.OrganizationService
 */
export declare const OrganizationService: GenService<{
  /**
   * @generated from rpc appsets.openapi.v1.OrganizationService.CreateOrganization
   */
  createOrganization: {
    methodKind: "unary";
    input: typeof CreateOrganizationRequestSchema;
    output: typeof CreateOrganizationResponseSchema;
  },
}>;

