// @generated by protoc-gen-es v2.10.0
// @generated from file openapi/v1/organization.proto (package appsets.openapi.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../google/api/annotations_pb";

/**
 * Describes the file openapi/v1/organization.proto.
 */
export const file_openapi_v1_organization = /*@__PURE__*/
  fileDesc("Ch1vcGVuYXBpL3YxL29yZ2FuaXphdGlvbi5wcm90bxISYXBwc2V0cy5vcGVuYXBpLnYxImkKGUNyZWF0ZU9yZ2FuaXphdGlvblJlcXVlc3QSCgoCaWQYASABKAkSDAoEY29kZRgCIAEoCRIMCgRuYW1lGAMgASgJEhAKCG93bmVkX2J5GAQgASgJEhIKCmNyZWF0ZWRfYnkYBSABKAkiHAoaQ3JlYXRlT3JnYW5pemF0aW9uUmVzcG9uc2UyswEKE09yZ2FuaXphdGlvblNlcnZpY2USmwEKEkNyZWF0ZU9yZ2FuaXphdGlvbhItLmFwcHNldHMub3BlbmFwaS52MS5DcmVhdGVPcmdhbml6YXRpb25SZXF1ZXN0Gi4uYXBwc2V0cy5vcGVuYXBpLnYxLkNyZWF0ZU9yZ2FuaXphdGlvblJlc3BvbnNlIiaC0+STAiA6ASoiGy9hcGkvdjEvb3JnYW5pemF0aW9uL2NyZWF0ZUI1WjNnaXRodWIuY29tL2FwcHNldHMvcHJvdG9jb2wvZ28vb3BlbmFwaS92MTtvcGVuYXBpcGJiBnByb3RvMw", [file_google_api_annotations]);

/**
 * Describes the message appsets.openapi.v1.CreateOrganizationRequest.
 * Use `create(CreateOrganizationRequestSchema)` to create a new message.
 */
export const CreateOrganizationRequestSchema = /*@__PURE__*/
  messageDesc(file_openapi_v1_organization, 0);

/**
 * Describes the message appsets.openapi.v1.CreateOrganizationResponse.
 * Use `create(CreateOrganizationResponseSchema)` to create a new message.
 */
export const CreateOrganizationResponseSchema = /*@__PURE__*/
  messageDesc(file_openapi_v1_organization, 1);

/**
 * @generated from service appsets.openapi.v1.OrganizationService
 */
export const OrganizationService = /*@__PURE__*/
  serviceDesc(file_openapi_v1_organization, 0);

