// @generated by protoc-gen-es v2.10.0
// @generated from file openapi/v1/organization.proto (package appsets.openapi.v1, syntax proto3)
/* eslint-disable */

// buf:lint:ignore PACKAGE_DIRECTORY_MATCH

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../google/api/annotations_pb";
import { file_google_rpc_status } from "../../google/rpc/status_pb";

/**
 * Describes the file openapi/v1/organization.proto.
 */
export const file_openapi_v1_organization = /*@__PURE__*/
  fileDesc("Ch1vcGVuYXBpL3YxL29yZ2FuaXphdGlvbi5wcm90bxISYXBwc2V0cy5vcGVuYXBpLnYxImkKGUNyZWF0ZU9yZ2FuaXphdGlvblJlcXVlc3QSCgoCaWQYASABKAkSDAoEY29kZRgCIAEoCRIMCgRuYW1lGAMgASgJEhAKCG93bmVkX2J5GAQgASgJEhIKCmNyZWF0ZWRfYnkYBSABKAkiPwoaQ3JlYXRlT3JnYW5pemF0aW9uUmVzcG9uc2USIQoFZXJyb3IYASABKAsyEi5nb29nbGUucnBjLlN0YXR1czKzAQoTT3JnYW5pemF0aW9uU2VydmljZRKbAQoSQ3JlYXRlT3JnYW5pemF0aW9uEi0uYXBwc2V0cy5vcGVuYXBpLnYxLkNyZWF0ZU9yZ2FuaXphdGlvblJlcXVlc3QaLi5hcHBzZXRzLm9wZW5hcGkudjEuQ3JlYXRlT3JnYW5pemF0aW9uUmVzcG9uc2UiJoLT5JMCIDoBKiIbL2FwaS92MS9vcmdhbml6YXRpb24vY3JlYXRlQjVaM2dpdGh1Yi5jb20vYXBwc2V0cy9wcm90b2NvbC9nby9vcGVuYXBpL3YxO29wZW5hcGlwYmIGcHJvdG8z", [file_google_api_annotations, file_google_rpc_status]);

/**
 * Describes the message appsets.openapi.v1.CreateOrganizationRequest.
 * Use `create(CreateOrganizationRequestSchema)` to create a new message.
 */
export const CreateOrganizationRequestSchema = /*@__PURE__*/
  messageDesc(file_openapi_v1_organization, 0);

/**
 * Describes the message appsets.openapi.v1.CreateOrganizationResponse.
 * Use `create(CreateOrganizationResponseSchema)` to create a new message.
 */
export const CreateOrganizationResponseSchema = /*@__PURE__*/
  messageDesc(file_openapi_v1_organization, 1);

/**
 * @generated from service appsets.openapi.v1.OrganizationService
 */
export const OrganizationService = /*@__PURE__*/
  serviceDesc(file_openapi_v1_organization, 0);

