// @generated by protoc-gen-es v2.10.0
// @generated from file openapi/v1/schedule.proto (package appsets.openapi.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../google/api/annotations_pb";

/**
 * Describes the file openapi/v1/schedule.proto.
 */
export const file_openapi_v1_schedule = /*@__PURE__*/
  fileDesc("ChlvcGVuYXBpL3YxL3NjaGVkdWxlLnByb3RvEhJhcHBzZXRzLm9wZW5hcGkudjEiGgoYVmFsaWRhdGVQdXJjaGFzZXNSZXF1ZXN0IhsKGVZhbGlkYXRlUHVyY2hhc2VzUmVzcG9uc2UyswEKD1NjaGVkdWxlU2VydmljZRKfAQoRVmFsaWRhdGVQdXJjaGFzZXMSLC5hcHBzZXRzLm9wZW5hcGkudjEuVmFsaWRhdGVQdXJjaGFzZXNSZXF1ZXN0Gi0uYXBwc2V0cy5vcGVuYXBpLnYxLlZhbGlkYXRlUHVyY2hhc2VzUmVzcG9uc2UiLYLT5JMCJzoBKiIiL2FwaS92MS9zY2hlZHVsZS9wdXJjaGFzZS92YWxpZGF0ZUI1WjNnaXRodWIuY29tL2FwcHNldHMvcHJvdG9jb2wvZ28vb3BlbmFwaS92MTtvcGVuYXBpcGJiBnByb3RvMw", [file_google_api_annotations]);

/**
 * Describes the message appsets.openapi.v1.ValidatePurchasesRequest.
 * Use `create(ValidatePurchasesRequestSchema)` to create a new message.
 */
export const ValidatePurchasesRequestSchema = /*@__PURE__*/
  messageDesc(file_openapi_v1_schedule, 0);

/**
 * Describes the message appsets.openapi.v1.ValidatePurchasesResponse.
 * Use `create(ValidatePurchasesResponseSchema)` to create a new message.
 */
export const ValidatePurchasesResponseSchema = /*@__PURE__*/
  messageDesc(file_openapi_v1_schedule, 1);

/**
 * @generated from service appsets.openapi.v1.ScheduleService
 */
export const ScheduleService = /*@__PURE__*/
  serviceDesc(file_openapi_v1_schedule, 0);

