// @generated by protoc-gen-es v2.10.0
// @generated from file openapi/v1/schedule.proto (package appsets.openapi.v1, syntax proto3)
/* eslint-disable */

// buf:lint:ignore PACKAGE_DIRECTORY_MATCH

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Status } from "../../google/rpc/status_pb";

/**
 * Describes the file openapi/v1/schedule.proto.
 */
export declare const file_openapi_v1_schedule: GenFile;

/**
 * @generated from message appsets.openapi.v1.ValidatePurchasesRequest
 */
export declare type ValidatePurchasesRequest = Message<"appsets.openapi.v1.ValidatePurchasesRequest"> & {
};

/**
 * Describes the message appsets.openapi.v1.ValidatePurchasesRequest.
 * Use `create(ValidatePurchasesRequestSchema)` to create a new message.
 */
export declare const ValidatePurchasesRequestSchema: GenMessage<ValidatePurchasesRequest>;

/**
 * @generated from message appsets.openapi.v1.ValidatePurchasesResponse
 */
export declare type ValidatePurchasesResponse = Message<"appsets.openapi.v1.ValidatePurchasesResponse"> & {
  /**
   * @generated from field: google.rpc.Status error = 1;
   */
  error?: Status;
};

/**
 * Describes the message appsets.openapi.v1.ValidatePurchasesResponse.
 * Use `create(ValidatePurchasesResponseSchema)` to create a new message.
 */
export declare const ValidatePurchasesResponseSchema: GenMessage<ValidatePurchasesResponse>;

/**
 * @generated from service appsets.openapi.v1.ScheduleService
 */
export declare const ScheduleService: GenService<{
  /**
   * @generated from rpc appsets.openapi.v1.ScheduleService.ValidatePurchases
   */
  validatePurchases: {
    methodKind: "unary";
    input: typeof ValidatePurchasesRequestSchema;
    output: typeof ValidatePurchasesResponseSchema;
  },
}>;

