// @generated by protoc-gen-es v2.10.0
// @generated from file openapi/v1/user.proto (package appsets.openapi.v1, syntax proto3)
/* eslint-disable */

// buf:lint:ignore PACKAGE_DIRECTORY_MATCH

import { enumDesc, fileDesc, messageDesc, serviceDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../google/api/annotations_pb";
import { file_google_rpc_status } from "../../google/rpc/status_pb";

/**
 * Describes the file openapi/v1/user.proto.
 */
export const file_openapi_v1_user = /*@__PURE__*/
  fileDesc("ChVvcGVuYXBpL3YxL3VzZXIucHJvdG8SEmFwcHNldHMub3BlbmFwaS52MSIeCg5HZXRVc2VyUmVxdWVzdBIMCgRuYW1lGAEgASgJIjQKD0dldFVzZXJSZXNwb25zZRIhCgVlcnJvchgBIAEoCzISLmdvb2dsZS5ycGMuU3RhdHVzIhMKEUNyZWF0ZVVzZXJSZXF1ZXN0IoUBChJDcmVhdGVVc2VyUmVzcG9uc2USIQoFZXJyb3IYASABKAsyEi5nb29nbGUucnBjLlN0YXR1cxIKCgJpZBgCIAEoCRIMCgRjb2RlGAMgASgJEhQKDGRpc3BsYXlfbmFtZRgEIAEoCRINCgVlbWFpbBgFIAEoCRINCgVwaG9uZRgGIAEoCSqFAQoIVXNlclJvbGUSGQoVVVNFUl9ST0xFX1VOU1BFQ0lGSUVEEAASEwoPVVNFUl9ST0xFX0FETUlOEAESFwoTVVNFUl9ST0xFX0RFVkVMT1BFUhACEhgKFFVTRVJfUk9MRV9NQUlOVEFJTkVSEAMSFgoSVVNFUl9ST0xFX1JFQURPTkxZEAQy9QEKC1VzZXJTZXJ2aWNlEmwKA0dldBIiLmFwcHNldHMub3BlbmFwaS52MS5HZXRVc2VyUmVxdWVzdBojLmFwcHNldHMub3BlbmFwaS52MS5HZXRVc2VyUmVzcG9uc2UiHILT5JMCFjoBKiIRL2FwaS92MS91c2Vycy9nZXQSeAoGQ3JlYXRlEiUuYXBwc2V0cy5vcGVuYXBpLnYxLkNyZWF0ZVVzZXJSZXF1ZXN0GiYuYXBwc2V0cy5vcGVuYXBpLnYxLkNyZWF0ZVVzZXJSZXNwb25zZSIfgtPkkwIZOgEqIhQvYXBpL3YxL3VzZXJzL2NyZWF0ZUI1WjNnaXRodWIuY29tL2FwcHNldHMvcHJvdG9jb2wvZ28vb3BlbmFwaS92MTtvcGVuYXBpcGJiBnByb3RvMw", [file_google_api_annotations, file_google_rpc_status]);

/**
 * Describes the message appsets.openapi.v1.GetUserRequest.
 * Use `create(GetUserRequestSchema)` to create a new message.
 */
export const GetUserRequestSchema = /*@__PURE__*/
  messageDesc(file_openapi_v1_user, 0);

/**
 * Describes the message appsets.openapi.v1.GetUserResponse.
 * Use `create(GetUserResponseSchema)` to create a new message.
 */
export const GetUserResponseSchema = /*@__PURE__*/
  messageDesc(file_openapi_v1_user, 1);

/**
 * Describes the message appsets.openapi.v1.CreateUserRequest.
 * Use `create(CreateUserRequestSchema)` to create a new message.
 */
export const CreateUserRequestSchema = /*@__PURE__*/
  messageDesc(file_openapi_v1_user, 2);

/**
 * Describes the message appsets.openapi.v1.CreateUserResponse.
 * Use `create(CreateUserResponseSchema)` to create a new message.
 */
export const CreateUserResponseSchema = /*@__PURE__*/
  messageDesc(file_openapi_v1_user, 3);

/**
 * Describes the enum appsets.openapi.v1.UserRole.
 */
export const UserRoleSchema = /*@__PURE__*/
  enumDesc(file_openapi_v1_user, 0);

/**
 * @generated from enum appsets.openapi.v1.UserRole
 */
export const UserRole = /*@__PURE__*/
  tsEnum(UserRoleSchema);

/**
 * @generated from service appsets.openapi.v1.UserService
 */
export const UserService = /*@__PURE__*/
  serviceDesc(file_openapi_v1_user, 0);

