// @generated by protoc-gen-es v2.10.0
// @generated from file client/v1/account.proto (package appsets.api.client.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../google/api/annotations_pb";
import { file_google_protobuf_wrappers } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file client/v1/account.proto.
 */
export const file_client_v1_account = /*@__PURE__*/
  fileDesc("ChdjbGllbnQvdjEvYWNjb3VudC5wcm90bxIVYXBwc2V0cy5hcGkuY2xpZW50LnYxIpkBCgxBY2NvdW50RW1haWwSDQoFZW1haWwYASABKAkSEAoIcGFzc3dvcmQYAiABKAkSOwoEdmFycxgDIAMoCzItLmFwcHNldHMuYXBpLmNsaWVudC52MS5BY2NvdW50RW1haWwuVmFyc0VudHJ5GisKCVZhcnNFbnRyeRILCgNrZXkYASABKAkSDQoFdmFsdWUYAiABKAk6AjgBIo4BChhBdXRoZW50aWNhdGVFbWFpbFJlcXVlc3QSNAoHYWNjb3VudBgBIAEoCzIjLmFwcHNldHMuYXBpLmNsaWVudC52MS5BY2NvdW50RW1haWwSKgoGY3JlYXRlGAIgASgLMhouZ29vZ2xlLnByb3RvYnVmLkJvb2xWYWx1ZRIQCgh1c2VybmFtZRgDIAEoCSJ0CgdTZXNzaW9uEg8KB2NyZWF0ZWQYASABKAgSDQoFdG9rZW4YAyABKAkSFQoNcmVmcmVzaF90b2tlbhgEIAEoCRIyCgl1c2VyX2luZm8YBSABKAsyHy5hcHBzZXRzLmFwaS5jbGllbnQudjEuVXNlckluZm8icAoIVXNlckluZm8SCgoCaWQYASABKAMSEAoIdXNlcm5hbWUYAiABKAkSFAoMZGlzcGxheV9uYW1lGAMgASgJEhIKCmF2YXRhcl91cmwYBCABKAkSDQoFZW1haWwYBSABKAkSDQoFcGhvbmUYBiABKAkiJAoTUmVmcmVzaFRva2VuUmVxdWVzdBINCgV0b2tlbhgBIAEoCTKqAgoOQWNjb3VudFNlcnZpY2USiwEKEUF1dGhlbnRpY2F0ZUVtYWlsEi8uYXBwc2V0cy5hcGkuY2xpZW50LnYxLkF1dGhlbnRpY2F0ZUVtYWlsUmVxdWVzdBoeLmFwcHNldHMuYXBpLmNsaWVudC52MS5TZXNzaW9uIiWC0+STAh86ASoiGi9hcGkvdjEvYXV0aGVudGljYXRlL2VtYWlsEokBCgxSZWZyZXNoVG9rZW4SKi5hcHBzZXRzLmFwaS5jbGllbnQudjEuUmVmcmVzaFRva2VuUmVxdWVzdBoeLmFwcHNldHMuYXBpLmNsaWVudC52MS5TZXNzaW9uIi2C0+STAic6ASoiIi9hcGkvdjEvYXV0aGVudGljYXRlL3Rva2VuL3JlZnJlc2hCM1oxZ2l0aHViLmNvbS9hcHBzZXRzL3Byb3RvY29sL2dvL2NsaWVudC92MTtjbGllbnRwYmIGcHJvdG8z", [file_google_api_annotations, file_google_protobuf_wrappers]);

/**
 * Describes the message appsets.api.client.v1.AccountEmail.
 * Use `create(AccountEmailSchema)` to create a new message.
 */
export const AccountEmailSchema = /*@__PURE__*/
  messageDesc(file_client_v1_account, 0);

/**
 * Describes the message appsets.api.client.v1.AuthenticateEmailRequest.
 * Use `create(AuthenticateEmailRequestSchema)` to create a new message.
 */
export const AuthenticateEmailRequestSchema = /*@__PURE__*/
  messageDesc(file_client_v1_account, 1);

/**
 * Describes the message appsets.api.client.v1.Session.
 * Use `create(SessionSchema)` to create a new message.
 */
export const SessionSchema = /*@__PURE__*/
  messageDesc(file_client_v1_account, 2);

/**
 * Describes the message appsets.api.client.v1.UserInfo.
 * Use `create(UserInfoSchema)` to create a new message.
 */
export const UserInfoSchema = /*@__PURE__*/
  messageDesc(file_client_v1_account, 3);

/**
 * Describes the message appsets.api.client.v1.RefreshTokenRequest.
 * Use `create(RefreshTokenRequestSchema)` to create a new message.
 */
export const RefreshTokenRequestSchema = /*@__PURE__*/
  messageDesc(file_client_v1_account, 4);

/**
 * @generated from service appsets.api.client.v1.AccountService
 */
export const AccountService = /*@__PURE__*/
  serviceDesc(file_client_v1_account, 0);

