// @generated by protoc-gen-es v2.10.0
// @generated from file client/v1/echo.proto (package appsets.api.client.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../google/api/annotations_pb";

/**
 * Describes the file client/v1/echo.proto.
 */
export const file_client_v1_echo = /*@__PURE__*/
  fileDesc("ChRjbGllbnQvdjEvZWNoby5wcm90bxIVYXBwc2V0cy5hcGkuY2xpZW50LnYxIh4KDVN0cmluZ01lc3NhZ2USDQoFdmFsdWUYASABKAkyegoLRWNob1NlcnZpY2USawoERWNobxIkLmFwcHNldHMuYXBpLmNsaWVudC52MS5TdHJpbmdNZXNzYWdlGiQuYXBwc2V0cy5hcGkuY2xpZW50LnYxLlN0cmluZ01lc3NhZ2UiF4LT5JMCEToBKiIML2FwaS92MS9lY2hvQjNaMWdpdGh1Yi5jb20vYXBwc2V0cy9wcm90b2NvbC9nby9jbGllbnQvdjE7Y2xpZW50cGJiBnByb3RvMw", [file_google_api_annotations]);

/**
 * Describes the message appsets.api.client.v1.StringMessage.
 * Use `create(StringMessageSchema)` to create a new message.
 */
export const StringMessageSchema = /*@__PURE__*/
  messageDesc(file_client_v1_echo, 0);

/**
 * @generated from service appsets.api.client.v1.EchoService
 */
export const EchoService = /*@__PURE__*/
  serviceDesc(file_client_v1_echo, 0);

