// @generated by protoc-gen-es v2.10.0
// @generated from file client/v1/echo.proto (package appsets.api.client.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file client/v1/echo.proto.
 */
export declare const file_client_v1_echo: GenFile;

/**
 * @generated from message appsets.api.client.v1.StringMessage
 */
export declare type StringMessage = Message<"appsets.api.client.v1.StringMessage"> & {
  /**
   * @generated from field: string value = 1;
   */
  value: string;
};

/**
 * Describes the message appsets.api.client.v1.StringMessage.
 * Use `create(StringMessageSchema)` to create a new message.
 */
export declare const StringMessageSchema: GenMessage<StringMessage>;

/**
 * @generated from service appsets.api.client.v1.EchoService
 */
export declare const EchoService: GenService<{
  /**
   * @generated from rpc appsets.api.client.v1.EchoService.Echo
   */
  echo: {
    methodKind: "unary";
    input: typeof StringMessageSchema;
    output: typeof StringMessageSchema;
  },
}>;

