// @generated by protoc-gen-es v2.10.0
// @generated from file client/v1/purchase.proto (package appsets.api.client.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../google/api/annotations_pb";

/**
 * Describes the file client/v1/purchase.proto.
 */
export const file_client_v1_purchase = /*@__PURE__*/
  fileDesc("ChhjbGllbnQvdjEvcHVyY2hhc2UucHJvdG8SFWFwcHNldHMuYXBpLmNsaWVudC52MSLMAgofSW5pdGlhbGl6ZVB1cmNoYXNlQWxpcGF5UmVxdWVzdBIUCgxwcm9kdWN0X3R5cGUYASABKAkSEgoKcHJvZHVjdF9pZBgCIAEoCRINCgVjb3VudBgDIAEoAxINCgVwcmljZRgEIAEoAxIUCgxhY3R1YWxfcHJpY2UYBSABKAMSFAoMdG90YWxfYW1vdW50GAYgASgDEhsKE2FjdHVhbF90b3RhbF9hbW91bnQYByABKAMSDwoHY29tbWVudBgIIAEoCRJWCghtZXRhZGF0YRgJIAMoCzJELmFwcHNldHMuYXBpLmNsaWVudC52MS5Jbml0aWFsaXplUHVyY2hhc2VBbGlwYXlSZXF1ZXN0Lk1ldGFkYXRhRW50cnkaLwoNTWV0YWRhdGFFbnRyeRILCgNrZXkYASABKAkSDQoFdmFsdWUYAiABKAk6AjgBIl8KIEluaXRpYWxpemVQdXJjaGFzZUFsaXBheVJlc3BvbnNlEhYKDnRyYW5zYWN0aW9uX2lkGAEgASgJEg8KB3BheWxvYWQYAiABKAkSEgoKZXhwaXJlZF9hdBgDIAEoAyIfCh1WYWxpZGF0ZVB1cmNoYXNlQWxpcGF5UmVxdWVzdCIgCh5WYWxpZGF0ZVB1cmNoYXNlQWxpcGF5UmVzcG9uc2UiLwoVQ2FuY2VsUHVyY2hhc2VSZXF1ZXN0EhYKDnRyYW5zYWN0aW9uX2lkGAEgASgJIhgKFkNhbmNlbFB1cmNoYXNlUmVzcG9uc2UylwQKD1B1cmNoYXNlU2VydmljZRK6AQoYSW5pdGlhbGl6ZVB1cmNoYXNlQWxpcGF5EjYuYXBwc2V0cy5hcGkuY2xpZW50LnYxLkluaXRpYWxpemVQdXJjaGFzZUFsaXBheVJlcXVlc3QaNy5hcHBzZXRzLmFwaS5jbGllbnQudjEuSW5pdGlhbGl6ZVB1cmNoYXNlQWxpcGF5UmVzcG9uc2UiLYLT5JMCJzoBKiIiL2FwaS92MS9wdXJjaGFzZS9hbGlwYXkvaW5pdGlhbGl6ZRKyAQoWVmFsaWRhdGVQdXJjaGFzZUFsaXBheRI0LmFwcHNldHMuYXBpLmNsaWVudC52MS5WYWxpZGF0ZVB1cmNoYXNlQWxpcGF5UmVxdWVzdBo1LmFwcHNldHMuYXBpLmNsaWVudC52MS5WYWxpZGF0ZVB1cmNoYXNlQWxpcGF5UmVzcG9uc2UiK4LT5JMCJToBKiIgL2FwaS92MS9wdXJjaGFzZS9hbGlwYXkvdmFsaWRhdGUSkQEKDkNhbmNlbFB1cmNoYXNlEiwuYXBwc2V0cy5hcGkuY2xpZW50LnYxLkNhbmNlbFB1cmNoYXNlUmVxdWVzdBotLmFwcHNldHMuYXBpLmNsaWVudC52MS5DYW5jZWxQdXJjaGFzZVJlc3BvbnNlIiKC0+STAhw6ASoiFy9hcGkvdjEvcHVyY2hhc2UvY2FuY2VsQjNaMWdpdGh1Yi5jb20vYXBwc2V0cy9wcm90b2NvbC9nby9jbGllbnQvdjE7Y2xpZW50cGJiBnByb3RvMw", [file_google_api_annotations]);

/**
 * Describes the message appsets.api.client.v1.InitializePurchaseAlipayRequest.
 * Use `create(InitializePurchaseAlipayRequestSchema)` to create a new message.
 */
export const InitializePurchaseAlipayRequestSchema = /*@__PURE__*/
  messageDesc(file_client_v1_purchase, 0);

/**
 * Describes the message appsets.api.client.v1.InitializePurchaseAlipayResponse.
 * Use `create(InitializePurchaseAlipayResponseSchema)` to create a new message.
 */
export const InitializePurchaseAlipayResponseSchema = /*@__PURE__*/
  messageDesc(file_client_v1_purchase, 1);

/**
 * Describes the message appsets.api.client.v1.ValidatePurchaseAlipayRequest.
 * Use `create(ValidatePurchaseAlipayRequestSchema)` to create a new message.
 */
export const ValidatePurchaseAlipayRequestSchema = /*@__PURE__*/
  messageDesc(file_client_v1_purchase, 2);

/**
 * Describes the message appsets.api.client.v1.ValidatePurchaseAlipayResponse.
 * Use `create(ValidatePurchaseAlipayResponseSchema)` to create a new message.
 */
export const ValidatePurchaseAlipayResponseSchema = /*@__PURE__*/
  messageDesc(file_client_v1_purchase, 3);

/**
 * Describes the message appsets.api.client.v1.CancelPurchaseRequest.
 * Use `create(CancelPurchaseRequestSchema)` to create a new message.
 */
export const CancelPurchaseRequestSchema = /*@__PURE__*/
  messageDesc(file_client_v1_purchase, 4);

/**
 * Describes the message appsets.api.client.v1.CancelPurchaseResponse.
 * Use `create(CancelPurchaseResponseSchema)` to create a new message.
 */
export const CancelPurchaseResponseSchema = /*@__PURE__*/
  messageDesc(file_client_v1_purchase, 5);

/**
 * @generated from service appsets.api.client.v1.PurchaseService
 */
export const PurchaseService = /*@__PURE__*/
  serviceDesc(file_client_v1_purchase, 0);

