// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: client/v1/echo.proto

package clientpb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StringMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringMessage) Reset() {
	*x = StringMessage{}
	mi := &file_client_v1_echo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringMessage) ProtoMessage() {}

func (x *StringMessage) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_echo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringMessage.ProtoReflect.Descriptor instead.
func (*StringMessage) Descriptor() ([]byte, []int) {
	return file_client_v1_echo_proto_rawDescGZIP(), []int{0}
}

func (x *StringMessage) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_client_v1_echo_proto protoreflect.FileDescriptor

const file_client_v1_echo_proto_rawDesc = "" +
	"\n" +
	"\x14client/v1/echo.proto\x12\x15appsets.api.client.v1\x1a\x1cgoogle/api/annotations.proto\"%\n" +
	"\rStringMessage\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value2z\n" +
	"\vEchoService\x12k\n" +
	"\x04Echo\x12$.appsets.api.client.v1.StringMessage\x1a$.appsets.api.client.v1.StringMessage\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/api/v1/echoB3Z1github.com/appsets/protocol/go/client/v1;clientpbb\x06proto3"

var (
	file_client_v1_echo_proto_rawDescOnce sync.Once
	file_client_v1_echo_proto_rawDescData []byte
)

func file_client_v1_echo_proto_rawDescGZIP() []byte {
	file_client_v1_echo_proto_rawDescOnce.Do(func() {
		file_client_v1_echo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_client_v1_echo_proto_rawDesc), len(file_client_v1_echo_proto_rawDesc)))
	})
	return file_client_v1_echo_proto_rawDescData
}

var file_client_v1_echo_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_client_v1_echo_proto_goTypes = []any{
	(*StringMessage)(nil), // 0: appsets.api.client.v1.StringMessage
}
var file_client_v1_echo_proto_depIdxs = []int32{
	0, // 0: appsets.api.client.v1.EchoService.Echo:input_type -> appsets.api.client.v1.StringMessage
	0, // 1: appsets.api.client.v1.EchoService.Echo:output_type -> appsets.api.client.v1.StringMessage
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_client_v1_echo_proto_init() }
func file_client_v1_echo_proto_init() {
	if File_client_v1_echo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_client_v1_echo_proto_rawDesc), len(file_client_v1_echo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_client_v1_echo_proto_goTypes,
		DependencyIndexes: file_client_v1_echo_proto_depIdxs,
		MessageInfos:      file_client_v1_echo_proto_msgTypes,
	}.Build()
	File_client_v1_echo_proto = out.File
	file_client_v1_echo_proto_goTypes = nil
	file_client_v1_echo_proto_depIdxs = nil
}
